.TH "com.example.photopage.config.WebConfig" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.config.WebConfig
.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy WebMvcConfigurer\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBaddResourceHandlers\fP (ResourceHandlerRegistry registry)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
