.TH "com.example.photopage.controller.FollowerController" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.controller.FollowerController
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "ResponseEntity<?> \fBgetFollowersCount\fP (@PathVariable Integer id)"
.br
.ti -1c
.RI "ResponseEntity<?> \fBgetFollowingCount\fP (@PathVariable Integer id)"
.br
.ti -1c
.RI "ResponseEntity<?> \fBfollowUser\fP (@PathVariable Integer followerId, @PathVariable Integer followedId)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
