.TH "com.example.photopage.repository.LikeRepository" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.repository.LikeRepository
.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy JpaRepository< Like, LikeId >\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "int \fBcountByPost_Id\fP (Integer postId)"
.br
.ti -1c
.RI "List< \fBLike\fP > \fBfindAllByUser_UserId\fP (Integer userId)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
