.TH "com.example.photopage.service.FollowerService" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.service.FollowerService
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "long \fBcountFollowers\fP (Integer userId)"
.br
.ti -1c
.RI "long \fBcountFollowing\fP (Integer userId)"
.br
.ti -1c
.RI "void \fBfollowUser\fP (Integer followerId, Integer followedId)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
