.TH "com.example.photopage.repository.FollowerRepository" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.repository.FollowerRepository
.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy JpaRepository< Follower, FollowerId >\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "long \fBcountByFollowed_UserId\fP (Integer userId)"
.br
.ti -1c
.RI "long \fBcountByFollower_UserId\fP (Integer userId)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
