.TH "com.example.photopage.service.PhotoService" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.service.PhotoService
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "String \fBsavePhoto\fP (MultipartFile file)  throws IOException "
.br
.ti -1c
.RI "\fBPhoto\fP \fBcreatePhotoRecord\fP (String path)"
.br
.ti -1c
.RI "\fBPhoto\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "void \fBdelete\fP (Integer id)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
