.TH "com.example.photopage.controller.AuthController" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.controller.AuthController
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "ResponseEntity< \fBUser\fP > \fBregister\fP (@RequestBody \fBRegisterRequest\fP req)"
.br
.ti -1c
.RI "ResponseEntity< \fBLoginResponse\fP > \fBlogin\fP (@RequestBody \fBLoginRequest\fP loginRequest, HttpServletResponse response)"
.br
.ti -1c
.RI "ResponseEntity< String > \fBforgotPassword\fP (@RequestBody ForgotPasswordRequest request)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
