.TH "com.example.photopage.model.User" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.model.User
.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy UserDetails\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "Collection<? extends GrantedAuthority > \fBgetAuthorities\fP ()"
.br
.ti -1c
.RI "String \fBgetUsername\fP ()"
.br
.ti -1c
.RI "boolean \fBisAccountNonExpired\fP ()"
.br
.ti -1c
.RI "boolean \fBisAccountNonLocked\fP ()"
.br
.ti -1c
.RI "boolean \fBisCredentialsNonExpired\fP ()"
.br
.ti -1c
.RI "boolean \fBisEnabled\fP ()"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
