.TH "com.example.photopage.service.UserService" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.service.UserService
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "List< \fBUser\fP > \fBallUsers\fP ()"
.br
.ti -1c
.RI "Optional< \fBUser\fP > \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "\fBUser\fP \fBsave\fP (\fBUser\fP user)"
.br
.ti -1c
.RI "\fBPhoto\fP \fBgetUserAvatar\fP (Integer userId)"
.br
.ti -1c
.RI "\fBUser\fP \fBupdateUser\fP (\fBUser\fP user, UpdateUserRequest request)"
.br
.ti -1c
.RI "void \fBchangePassword\fP (\fBUser\fP user, ChangePasswordRequest request)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
