.TH "com.example.photopage.repository.PhotoRepository" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.repository.PhotoRepository
.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy JpaRepository< Photo, Integer >\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
