.TH "com.example.photopage.exceptions.GlobalExceptionHandler" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.exceptions.GlobalExceptionHandler
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "ProblemDetail \fBhandleSecurityException\fP (Exception exception)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
