.TH "com.example.photopage.service.AuthenticationService" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.service.AuthenticationService
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBUser\fP \fBsignup\fP (\fBRegisterRequest\fP registerRequest)"
.br
.ti -1c
.RI "\fBUser\fP \fBlogin\fP (\fBLoginRequest\fP loginRequest)"
.br
.ti -1c
.RI "void \fBrequestPasswordReset\fP (String email)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
