.TH "com.example.photopage.config.SecurityConfig" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.config.SecurityConfig
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "CorsConfigurationSource \fBcorsConfigurationSource\fP ()"
.br
.ti -1c
.RI "SecurityFilterChain \fBsecurityFilterChain\fP (HttpSecurity http)  throws Exception "
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
