.TH "com.example.photopage.repository.PostRepository" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.photopage.repository.PostRepository
.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy JpaRepository< Post, Integer >\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "List< \fBPost\fP > \fBfindByOwner_UserId\fP (Integer userId)"
.br
.ti -1c
.RI "List< \fBPost\fP > \fBfindByOwner\fP (\fBUser\fP owner)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
