.TH "flatted._Known" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flatted._Known
.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "list \fBkey\fP = []"
.br
.ti -1c
.RI "list \fBvalue\fP = []"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
