.TH "Flatted" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flatted
.SH SYNOPSIS
.br
.PP
.SS "Statyczne metody publiczne"

.in +1c
.ti -1c
.RI "static \fBparse\fP ($json, $assoc=false, $depth=512, $options=0)"
.br
.ti -1c
.RI "static \fBstringify\fP ($value, $options=0, $depth=512)"
.br
.in -1c

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla PinterestApp\&.
