.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2typescript_2_s_e_c_u_r_i_t_y" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2typescript_2_s_e_c_u_r_i_t_y \- SECURITY 
.PP

.SS "Security"
Microsoft takes the security of our software products and services seriously, which includes all source code repositories managed through our GitHub organizations, which include \fRMicrosoft\fP, \fRAzure\fP, \fRDotNet\fP, \fRAspNet\fP and \fRXamarin\fP\&.

.PP
If you believe you have found a security vulnerability in any Microsoft-owned repository that meets \fRMicrosoft's definition of a security vulnerability\fP, please report it to us as described below\&.
.SS "Reporting Security Issues"
\fBPlease do not report security vulnerabilities through public GitHub issues\&.\fP

.PP
Instead, please report them to the Microsoft Security Response Center (MSRC) at \fRhttps://msrc\&.microsoft\&.com/create-report\fP\&.

.PP
If you prefer to submit without logging in, send email to \fRsecure@microsoft\&.com\fP\&. If possible, encrypt your message with our PGP key; please download it from the \fRMicrosoft Security Response Center PGP Key page\fP\&.

.PP
You should receive a response within 24 hours\&. If for some reason you do not, please follow up via email to ensure we received your original message\&. Additional information can be found at \fRmicrosoft\&.com/msrc\fP\&.

.PP
Please include the requested information listed below (as much as you can provide) to help us better understand the nature and scope of the possible issue:

.PP
.IP "\(bu" 2
Type of issue (e\&.g\&. buffer overflow, SQL injection, cross-site scripting, etc\&.)
.IP "\(bu" 2
Full paths of source file(s) related to the manifestation of the issue
.IP "\(bu" 2
The location of the affected source code (tag/branch/commit or direct URL)
.IP "\(bu" 2
Any special configuration required to reproduce the issue
.IP "\(bu" 2
Step-by-step instructions to reproduce the issue
.IP "\(bu" 2
Proof-of-concept or exploit code (if possible)
.IP "\(bu" 2
Impact of the issue, including how an attacker might exploit the issue
.PP

.PP
This information will help us triage your report more quickly\&.

.PP
If you are reporting for a bug bounty, more complete reports can contribute to a higher bounty award\&. Please visit our \fRMicrosoft Bug Bounty Program\fP page for more details about our active programs\&.
.SS "Preferred Languages"
We prefer all communications to be in English\&.
.SS "Policy"
Microsoft follows the principle of \fRCoordinated Vulnerability Disclosure\fP\&. 
