.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2es-object-atoms_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2es-object-atoms_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.1\&.1\fP - 2025-01-14"
.PP
.SS "Commits"
.IP "\(bu" 2
[types] \fRToObject\fP: improve types \fR\fRcfe8c8a\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2025-01-14"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRisObject\fP \fR\fR51e4042\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2025-01-13"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fR@ljharb/tsconfig\fP, \fR@types/tape\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fR38ab9eb\fP\fP
.IP "\(bu" 2
[types] improve types \fR\fR7d1beb8\fP\fP
.IP "\(bu" 2
[Tests] replace \fRaud\fP with \fRnpm audit\fP \fR\fR25863ba\fP\fP
.IP "\(bu" 2
[Dev Deps] add missing peer dep \fR\fRc012309\fP\fP
.PP
.SH "v1\&.0\&.0 - 2024-03-16"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme, types \fR\fRf1499db\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR99eedc7\fP\fP
.IP "\(bu" 2
[meta] rename repo \fR\fRfc851fa\fP\fP
.IP "\(bu" 2
npm init \fR\fRb909377\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR7249edd\fP\fP 
.PP

