.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2call-bind-apply-helpers_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2call-bind-apply-helpers_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.0\&.2\fP - 2025-02-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[types] improve inferred types \fR\fRe6f9586\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@arethetypeswrong/cli\fP, \fR@ljharb/tsconfig\fP, \fR@types/tape\fP, \fRes-value-fixtures\fP, \fRfor-each\fP, \fRhas-strict-mode\fP, \fRobject-inspect\fP \fR\fRe43d540\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2024-12-08"
.PP
.SS "Commits"
.IP "\(bu" 2
[types] \fRreflectApply\fP: fix types \fR\fR4efc396\fP\fP
.IP "\(bu" 2
[Fix] \fRreflectApply\fP: oops, Reflect is not a function \fR\fR83cc739\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@arethetypeswrong/cli\fP \fR\fR80bd5d3\fP\fP
.PP
.SH "v1\&.0\&.0 - 2024-12-05"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme \fR\fR7879629\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR3f1dc16\fP\fP
.IP "\(bu" 2
npm init \fR\fR081df04\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR5b9ca0f\fP\fP 
.PP

