.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2form-data_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2form-data_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv4\&.0\&.4\fP - 2025-07-16"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR811f682\fP\fP
.IP "\(bu" 2
[Tests] handle predict-v8-randomness failures in node < 17 and node > 23 \fR\fR1d11a76\fP\fP
.IP "\(bu" 2
[Fix] Switch to using \fRcrypto\fP random for boundary values \fR\fR3d17230\fP\fP
.IP "\(bu" 2
[Tests] fix linting errors \fR\fR5e34080\fP\fP
.IP "\(bu" 2
[meta] actually ensure the readme backup isn’t published \fR\fR316c82b\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP \fR\fR58c25d7\fP\fP
.IP "\(bu" 2
[meta] fix readme capitalization \fR\fR2300ca1\fP\fP
.PP
.SH "\fRv4\&.0\&.3\fP - 2025-06-05"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] \fRappend\fP: avoid a crash on nullish values \fR\fR#577\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[eslint] use a shared config \fR\fR426ba9a\fP\fP
.IP "\(bu" 2
[eslint] fix some spacing issues \fR\fR2094191\fP\fP
.IP "\(bu" 2
[Refactor] use \fRhasown\fP \fR\fR81ab41b\fP\fP
.IP "\(bu" 2
[Fix] validate boundary type in \fRsetBoundary()\fP method \fR\fR8d8e469\fP\fP
.IP "\(bu" 2
[Tests] add tests to check the behavior of \fRgetBoundary\fP with non-strings \fR\fR837b8a1\fP\fP
.IP "\(bu" 2
[Dev Deps] remove unused deps \fR\fR870e4e6\fP\fP
.IP "\(bu" 2
[meta] remove local commit hooks \fR\fRe6e83cc\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fR4066fd6\fP\fP
.IP "\(bu" 2
[meta] fix scripts to use prepublishOnly \fR\fRc4bbb13\fP\fP
.PP
.SH "\fRv4\&.0\&.2\fP - 2025-02-14"
.PP
.SS "Merged"
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available \fR\fR#573\fP\fP
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available \fR\fR#573\fP\fP
.IP "\(bu" 2
fix (npmignore): ignore temporary build files \fR\fR#532\fP\fP
.IP "\(bu" 2
fix (npmignore): ignore temporary build files \fR\fR#532\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available (#573) \fR\fR#396\fP\fP
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available (#573) \fR\fR#396\fP\fP
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available \fR\fR#396\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Merge tags v2\&.5\&.3 and v3\&.0\&.3 \fR\fR92613b9\fP\fP
.IP "\(bu" 2
[Tests] migrate from travis to GHA \fR\fR806eda7\fP\fP
.IP "\(bu" 2
[Tests] migrate from travis to GHA \fR\fR8fdb3bc\fP\fP
.IP "\(bu" 2
[Refactor] use \fRObject\&.prototype\&.hasOwnProperty\&.call\fP \fR\fR7fecefe\fP\fP
.IP "\(bu" 2
[Refactor] use \fRObject\&.prototype\&.hasOwnProperty\&.call\fP \fR\fR6e682d4\fP\fP
.IP "\(bu" 2
[Refactor] use \fRObject\&.prototype\&.hasOwnProperty\&.call\fP \fR\fRdf3c1e6\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/node\fP, \fRbrowserify\fP, \fRcoveralls\fP, \fRcross-spawn\fP, \fReslint\fP, \fRformidable\fP, \fRin-publish\fP, \fRpkgfiles\fP, \fRpre-commit\fP, \fRpuppeteer\fP, \fRrequest\fP, \fRtape\fP, \fRtypescript\fP \fR\fR8261fcb\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/node\fP, \fRbrowserify\fP, \fRcoveralls\fP, \fRcross-spawn\fP, \fReslint\fP, \fRformidable\fP, \fRin-publish\fP, \fRpkgfiles\fP, \fRpre-commit\fP, \fRpuppeteer\fP, \fRrequest\fP, \fRtape\fP, \fRtypescript\fP \fR\fRfb66cb7\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/node\fP, \fRbrowserify\fP, \fRcoveralls\fP, \fReslint\fP, \fRformidable\fP, \fRin-publish\fP, \fRphantomjs-prebuilt\fP, \fRpkgfiles\fP, \fRpre-commit\fP, \fRrequest\fP, \fRtape\fP, \fRtypescript\fP \fR\fR819f6b7\fP\fP
.IP "\(bu" 2
[eslint] clean up ignores \fR\fR3217b3d\fP\fP
.IP "\(bu" 2
[eslint] clean up ignores \fR\fR3a9d480\fP\fP
.IP "\(bu" 2
[Fix] \fRBuffer\&.from\fP and \fRBuffer\&.alloc\fP require node 4+ \fR\fRc499f76\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRb82f590\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRb170ee2\fP\fP
.IP "\(bu" 2
[Deps] update \fRcombined-stream\fP, \fRmime-types\fP \fR\fR6b1ca1d\fP\fP
.IP "\(bu" 2
[Dev Deps] pin \fRrequest\fP which via \fRtough-cookie\fP ^2\&.4 depends on \fRpsl\fP \fR\fRe5df7f2\fP\fP
.IP "\(bu" 2
[Deps] update \fRmime-types\fP \fR\fR5a5bafe\fP\fP
.IP "\(bu" 2
Bumped version 2\&.5\&.3 \fR\fR9457283\fP\fP
.IP "\(bu" 2
[Dev Deps] pin \fRrequest\fP which via \fRtough-cookie\fP ^2\&.4 depends on \fRpsl\fP \fR\fR9dbe192\fP\fP
.IP "\(bu" 2
Merge tags v2\&.5\&.2 and v3\&.0\&.2 \fR\fRd53265d\fP\fP
.IP "\(bu" 2
Bumped version 2\&.5\&.2 \fR\fR7020dd4\fP\fP
.IP "\(bu" 2
[Dev Deps] downgrade \fRcross-spawn\fP \fR\fR3fc1a9b\fP\fP
.IP "\(bu" 2
fix: move util\&.isArray to Array\&.isArray (#564) \fR\fRedb555a\fP\fP
.IP "\(bu" 2
fix: move util\&.isArray to Array\&.isArray (#564) \fR\fR10418d1\fP\fP
.PP
.SH "\fRv4\&.0\&.1\fP - 2024-10-10"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate from travis to GHA \fR\fR757b4e3\fP\fP
.IP "\(bu" 2
[eslint] clean up ignores \fR\fRe8f0d80\fP\fP
.IP "\(bu" 2
fix (npmignore): ignore temporary build files \fR\fR335ad19\fP\fP
.IP "\(bu" 2
fix: move util\&.isArray to Array\&.isArray \fR\fR440d3be\fP\fP
.PP
.SH "\fRv4\&.0\&.0\fP - 2021-02-15"
.PP
.SS "Merged"
.IP "\(bu" 2
Handle custom stream \fR\fR#382\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Fix typo \fR\fRe705c0a\fP\fP
.IP "\(bu" 2
Update README for custom stream behavior \fR\fR6dd8624\fP\fP
.PP
.SH "\fRv3\&.0\&.3\fP - 2025-02-14"
.PP
.SS "Merged"
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available \fR\fR#573\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available (#573) \fR\fR#396\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRObject\&.prototype\&.hasOwnProperty\&.call\fP \fR\fR7fecefe\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/node\fP, \fRbrowserify\fP, \fRcoveralls\fP, \fRcross-spawn\fP, \fReslint\fP, \fRformidable\fP, \fRin-publish\fP, \fRpkgfiles\fP, \fRpre-commit\fP, \fRpuppeteer\fP, \fRrequest\fP, \fRtape\fP, \fRtypescript\fP \fR\fR8261fcb\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRb82f590\fP\fP
.IP "\(bu" 2
[Dev Deps] pin \fRrequest\fP which via \fRtough-cookie\fP ^2\&.4 depends on \fRpsl\fP \fR\fRe5df7f2\fP\fP
.IP "\(bu" 2
[Deps] update \fRmime-types\fP \fR\fR5a5bafe\fP\fP
.PP
.SH "\fRv3\&.0\&.2\fP - 2024-10-10"
.PP
.SS "Merged"
.IP "\(bu" 2
fix (npmignore): ignore temporary build files \fR\fR#532\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate from travis to GHA \fR\fR8fdb3bc\fP\fP
.IP "\(bu" 2
[eslint] clean up ignores \fR\fR3217b3d\fP\fP
.IP "\(bu" 2
fix: move util\&.isArray to Array\&.isArray (#564) \fR\fRedb555a\fP\fP
.PP
.SH "\fRv3\&.0\&.1\fP - 2021-02-15"
.PP
.SS "Merged"
.IP "\(bu" 2
Fix typo: ads -> adds \fR\fR#451\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
feat: add setBoundary method \fR\fR55d90ce\fP\fP
.PP
.SH "\fRv3\&.0\&.0\fP - 2019-11-05"
.PP
.SS "Merged"
.IP "\(bu" 2
Update Readme\&.md \fR\fR#449\fP\fP
.IP "\(bu" 2
Update package\&.json \fR\fR#448\fP\fP
.IP "\(bu" 2
fix memory leak \fR\fR#447\fP\fP
.IP "\(bu" 2
form-data: Replaced PhantomJS Dependency \fR\fR#442\fP\fP
.IP "\(bu" 2
Fix constructor options in Typescript definitions \fR\fR#446\fP\fP
.IP "\(bu" 2
Fix the getHeaders method signatures \fR\fR#434\fP\fP
.IP "\(bu" 2
Update combined-stream (fixes #422) \fR\fR#424\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
Merge pull request #424 from botgram/update-combined-stream \fR\fR#422\fP\fP
.IP "\(bu" 2
Update combined-stream (fixes #422) \fR\fR#422\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Add readable stream options to constructor type \fR\fR80c8f74\fP\fP
.IP "\(bu" 2
Fixed: getHeaders method signatures \fR\fRf4ca7f8\fP\fP
.IP "\(bu" 2
Pass options to constructor if not used with new \fR\fR4bde68e\fP\fP
.IP "\(bu" 2
Make userHeaders optional \fR\fR2b4e478\fP\fP
.PP
.SH "\fRv2\&.5\&.3\fP - 2025-02-14"
.PP
.SS "Merged"
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available \fR\fR#573\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] set \fRSymbol\&.toStringTag\fP when available (#573) \fR\fR#396\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRObject\&.prototype\&.hasOwnProperty\&.call\fP \fR\fR6e682d4\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/node\fP, \fRbrowserify\fP, \fRcoveralls\fP, \fReslint\fP, \fRformidable\fP, \fRin-publish\fP, \fRphantomjs-prebuilt\fP, \fRpkgfiles\fP, \fRpre-commit\fP, \fRrequest\fP, \fRtape\fP, \fRtypescript\fP \fR\fR819f6b7\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRb170ee2\fP\fP
.IP "\(bu" 2
[Deps] update \fRcombined-stream\fP, \fRmime-types\fP \fR\fR6b1ca1d\fP\fP
.IP "\(bu" 2
Bumped version 2\&.5\&.3 \fR\fR9457283\fP\fP
.IP "\(bu" 2
[Dev Deps] pin \fRrequest\fP which via \fRtough-cookie\fP ^2\&.4 depends on \fRpsl\fP \fR\fR9dbe192\fP\fP
.PP
.SH "\fRv2\&.5\&.2\fP - 2024-10-10"
.PP
.SS "Merged"
.IP "\(bu" 2
fix (npmignore): ignore temporary build files \fR\fR#532\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate from travis to GHA \fR\fR806eda7\fP\fP
.IP "\(bu" 2
[eslint] clean up ignores \fR\fR3a9d480\fP\fP
.IP "\(bu" 2
[Fix] \fRBuffer\&.from\fP and \fRBuffer\&.alloc\fP require node 4+ \fR\fRc499f76\fP\fP
.IP "\(bu" 2
Bumped version 2\&.5\&.2 \fR\fR7020dd4\fP\fP
.IP "\(bu" 2
[Dev Deps] downgrade \fRcross-spawn\fP \fR\fR3fc1a9b\fP\fP
.IP "\(bu" 2
fix: move util\&.isArray to Array\&.isArray (#564) \fR\fR10418d1\fP\fP
.PP
.SH "\fRv2\&.5\&.1\fP - 2019-08-28"
.PP
.SS "Merged"
.IP "\(bu" 2
Fix error in callback signatures \fR\fR#435\fP\fP
.IP "\(bu" 2
-Fixed: Eerror in the documentations as indicated in #439 \fR\fR#440\fP\fP
.IP "\(bu" 2
Add constructor options to TypeScript defs \fR\fR#437\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Add remaining combined-stream options to typedef \fR\fR4d41a32\fP\fP
.IP "\(bu" 2
Bumped version 2\&.5\&.1 \fR\fR8ce81f5\fP\fP
.IP "\(bu" 2
Bump rimraf to 2\&.7\&.1 \fR\fRa6bc2d4\fP\fP
.PP
.SH "\fRv2\&.5\&.0\fP - 2019-07-03"
.PP
.SS "Merged"
.IP "\(bu" 2
- Added: public methods with information and examples to readme \fR\fR#429\fP\fP
.IP "\(bu" 2
chore: move @types/node to devDep \fR\fR#431\fP\fP
.IP "\(bu" 2
Switched windows tests from AppVeyor to Travis \fR\fR#430\fP\fP
.IP "\(bu" 2
feat(typings): migrate TS typings #427 \fR\fR#428\fP\fP
.IP "\(bu" 2
enhance the method of path\&.basename, handle undefined case \fR\fR#421\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
- Added: public methods with information and examples to the readme file\&. \fR\fR21323f3\fP\fP
.IP "\(bu" 2
feat(typings): migrate TS typings \fR\fRa3c0142\fP\fP
.IP "\(bu" 2
- Fixed: Typos \fR\fR37350fa\fP\fP
.IP "\(bu" 2
Switched to Travis Windows from Appveyor \fR\fRfc61c73\fP\fP
.IP "\(bu" 2
- Fixed: rendering of subheaders \fR\fRe93ed8d\fP\fP
.IP "\(bu" 2
Updated deps and readme \fR\fRe3d8628\fP\fP
.IP "\(bu" 2
Updated dependencies \fR\fR19add50\fP\fP
.IP "\(bu" 2
Bumped version to 2\&.5\&.0 \fR\fR905f173\fP\fP
.IP "\(bu" 2
- Fixed: filesize is not a valid option? knownLength should be used for streams \fR\fRd88f912\fP\fP
.IP "\(bu" 2
Bump notion of modern node to node8 \fR\fR508b626\fP\fP
.IP "\(bu" 2
enhance the method of path\&.basename \fR\fRfaaa68a\fP\fP
.PP
.SH "\fRv2\&.4\&.0\fP - 2019-06-19"
.PP
.SS "Merged"
.IP "\(bu" 2
Added "getBuffer" method and updated certificates \fR\fR#419\fP\fP
.IP "\(bu" 2
docs(readme): add axios integration document \fR\fR#425\fP\fP
.IP "\(bu" 2
Allow newer versions of combined-stream \fR\fR#402\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Updated: Certificate \fR\fRe90a76a\fP\fP
.IP "\(bu" 2
Updated build/test/badges \fR\fR8512eef\fP\fP
.IP "\(bu" 2
Bumped version 2\&.4\&.0 \fR\fR0f8da06\fP\fP
.IP "\(bu" 2
docs(readme): remove unnecessary bracket \fR\fR4e3954d\fP\fP
.IP "\(bu" 2
Bumped version to 2\&.3\&.3 \fR\fRb16916a\fP\fP
.PP
.SH "\fRv2\&.3\&.2\fP - 2018-02-13"
.PP
.SS "Merged"
.IP "\(bu" 2
Pulling in fixed combined-stream \fR\fR#379\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
All the dev dependencies are breaking in old versions of node :'( \fR\fRc7dba6a\fP\fP
.IP "\(bu" 2
Updated badges \fR\fR19b6c7a\fP\fP
.IP "\(bu" 2
Try tests in node@4 \fR\fR872a326\fP\fP
.IP "\(bu" 2
Pull in final version \fR\fR9d44871\fP\fP
.PP
.SH "\fRv2\&.3\&.1\fP - 2017-08-24"
.PP
.SS "Commits"
.IP "\(bu" 2
Updated readme with custom options example \fR\fR8e0a569\fP\fP
.IP "\(bu" 2
Added support (tests) for node 8 \fR\fRd1d6f4a\fP\fP
.PP
.SH "\fRv2\&.3\&.0\fP - 2017-08-24"
.PP
.SS "Merged"
.IP "\(bu" 2
Added custom \fRoptions\fP support \fR\fR#368\fP\fP
.IP "\(bu" 2
Allow form\&.submit with url string param to use https \fR\fR#249\fP\fP
.IP "\(bu" 2
Proper header production \fR\fR#357\fP\fP
.IP "\(bu" 2
Fix wrong MIME type in example \fR\fR#285\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
allow form\&.submit with url string param to use https \fR\fRc0390dc\fP\fP
.IP "\(bu" 2
update tests for url parsing \fR\fReec0e80\fP\fP
.IP "\(bu" 2
Uses for in to assign properties instead of Object\&.assign \fR\fRf6854ed\fP\fP
.IP "\(bu" 2
Adds test to check for option override \fR\fR61762f2\fP\fP
.IP "\(bu" 2
Removes the 2mb maxDataSize limitation \fR\fRdc171c3\fP\fP
.IP "\(bu" 2
Ignore \&.DS_Store \fR\fRe8a05d3\fP\fP
.PP
.SH "\fRv2\&.2\&.0\fP - 2017-06-11"
.PP
.SS "Merged"
.IP "\(bu" 2
Filename can be a nested path \fR\fR#355\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Bumped version number\&. \fR\fRd7398c3\fP\fP
.PP
.SH "\fRv2\&.1\&.4\fP - 2017-04-08"
.PP
.SH "\fR2\&.1\&.3\fP - 2017-04-08"
.PP
.SH "\fRv2\&.1\&.3\fP - 2017-04-08"
.PP
.SS "Merged"
.IP "\(bu" 2
toString should output '[object FormData]' \fR\fR#346\fP\fP
.PP
.SH "\fRv2\&.1\&.2\fP - 2016-11-07"
.PP
.SS "Merged"
.IP "\(bu" 2
#271 Added check for self and window objects + tests \fR\fR#282\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Added check for self and window objects + tests \fR\fRc99e4ec\fP\fP
.PP
.SH "\fRv2\&.1\&.1\fP - 2016-10-03"
.PP
.SS "Merged"
.IP "\(bu" 2
Bumped dependencies\&. \fR\fR#270\fP\fP
.IP "\(bu" 2
Update browser\&.js shim to use self instead of window \fR\fR#267\fP\fP
.IP "\(bu" 2
Boilerplate code rediction \fR\fR#265\fP\fP
.IP "\(bu" 2
eslint@3\&.7\&.0 \fR\fR#266\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
code duplicates removed \fR\fRe9239fb\fP\fP
.IP "\(bu" 2
Changed according to requests \fR\fRaa99246\fP\fP
.IP "\(bu" 2
chore(package): update eslint to version 3\&.7\&.0 \fR\fR090a859\fP\fP
.PP
.SH "\fRv2\&.1\&.0\fP - 2016-09-25"
.PP
.SS "Merged"
.IP "\(bu" 2
Added \fRhasKnownLength\fP public method \fR\fR#263\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Added hasKnownLength public method \fR\fR655b959\fP\fP
.PP
.SH "\fRv2\&.0\&.0\fP - 2016-09-16"
.PP
.SS "Merged"
.IP "\(bu" 2
Replaced async with asynckit \fR\fR#258\fP\fP
.IP "\(bu" 2
Pre-release house cleaning \fR\fR#247\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Replaced async with asynckit\&. Modernized \fR\fR1749b78\fP\fP
.IP "\(bu" 2
Ignore \&.bak files \fR\fRc08190a\fP\fP
.IP "\(bu" 2
Trying to be more chatty\&. :) \fR\fRc79eabb\fP\fP
.PP
.SH "\fRv1\&.0\&.0\fP - 2016-08-26"
.PP
.SS "Merged"
.IP "\(bu" 2
Allow custom header fields to be set as an object\&. \fR\fR#190\fP\fP
.IP "\(bu" 2
v1\&.0\&.0-rc4 \fR\fR#182\fP\fP
.IP "\(bu" 2
Avoid undefined variable reference in older browsers \fR\fR#176\fP\fP
.IP "\(bu" 2
More housecleaning \fR\fR#164\fP\fP
.IP "\(bu" 2
More cleanup \fR\fR#159\fP\fP
.IP "\(bu" 2
Added windows testing\&. Some cleanup\&. \fR\fR#158\fP\fP
.IP "\(bu" 2
Housecleaning\&. Added test coverage\&. \fR\fR#156\fP\fP
.IP "\(bu" 2
Second iteration of cleanup\&. \fR\fR#145\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Pre-release house cleaning \fR\fR440d72b\fP\fP
.IP "\(bu" 2
Updated deps, updated docs \fR\fR54b6114\fP\fP
.IP "\(bu" 2
make docs up-to-date \fR\fR5e383d7\fP\fP
.IP "\(bu" 2
Added missing deps \fR\fRfe04862\fP\fP
.PP
.SH "\fRv1\&.0\&.0-rc4\fP - 2016-03-15"
.PP
.SS "Merged"
.IP "\(bu" 2
Housecleaning, preparing for the release \fR\fR#144\fP\fP
.IP "\(bu" 2
lib: emit error when failing to get length \fR\fR#127\fP\fP
.IP "\(bu" 2
Cleaning up for Codacity 2\&. \fR\fR#143\fP\fP
.IP "\(bu" 2
Cleaned up codacity concerns\&. \fR\fR#142\fP\fP
.IP "\(bu" 2
Should throw type error without new operator\&. \fR\fR#129\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
More cleanup \fR\fR94b6565\fP\fP
.IP "\(bu" 2
Shuffling things around \fR\fR3c2f172\fP\fP
.IP "\(bu" 2
Second iteration of cleanup\&. \fR\fR347c88e\fP\fP
.IP "\(bu" 2
Housecleaning \fR\fRc335610\fP\fP
.IP "\(bu" 2
More housecleaning \fR\fRf573321\fP\fP
.IP "\(bu" 2
Trying to make far run on windows\&. + cleanup \fR\fRe426dfc\fP\fP
.IP "\(bu" 2
Playing with appveyor \fR\fRc9458a7\fP\fP
.IP "\(bu" 2
Updated dev dependencies\&. \fR\fRceebe88\fP\fP
.IP "\(bu" 2
Replaced win-spawn with cross-spawn \fR\fR405a69e\fP\fP
.IP "\(bu" 2
Updated readme badges\&. \fR\fR12f282a\fP\fP
.IP "\(bu" 2
Making paths windows friendly\&. \fR\fRf4bddc5\fP\fP
.IP "\(bu" 2
[WIP] trying things for greater sanity \fR\fR8ad1f02\fP\fP
.IP "\(bu" 2
Bending under Codacy \fR\fRbfff3bb\fP\fP
.IP "\(bu" 2
Another attempt to make windows friendly \fR\fRf3eb628\fP\fP
.IP "\(bu" 2
Updated dependencies\&. \fR\fRf73996e\fP\fP
.IP "\(bu" 2
Missed travis changes\&. \fR\fR67ee79f\fP\fP
.IP "\(bu" 2
Restructured badges\&. \fR\fR48444a1\fP\fP
.IP "\(bu" 2
Add similar type error as the browser for attempting to use form-data without new\&. \fR\fR5711320\fP\fP
.IP "\(bu" 2
Took out codeclimate-test-reporter \fR\fRa7e0c65\fP\fP
.IP "\(bu" 2
One more \fR\fR8e84cff\fP\fP
.PP
.SH "\fRv1\&.0\&.0-rc3\fP - 2015-07-29"
.PP
.SS "Merged"
.IP "\(bu" 2
House cleaning\&. Added \fRpre-commit\fP\&. \fR\fR#140\fP\fP
.IP "\(bu" 2
Allow custom content-type without setting a filename\&. \fR\fR#138\fP\fP
.IP "\(bu" 2
Add node-fetch to alternative submission methods\&. \fR\fR#132\fP\fP
.IP "\(bu" 2
Update dependencies \fR\fR#130\fP\fP
.IP "\(bu" 2
Switching to container based TravisCI \fR\fR#136\fP\fP
.IP "\(bu" 2
Default content-type to 'application/octect-stream' \fR\fR#128\fP\fP
.IP "\(bu" 2
Allow filename as third option of \&.append \fR\fR#125\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Allow custom content-type without setting a filename \fR\fRc8a77cc\fP\fP
.IP "\(bu" 2
Fixed ranged test\&. \fR\fRa5ac58c\fP\fP
.IP "\(bu" 2
Allow filename as third option of #append \fR\fRd081005\fP\fP
.IP "\(bu" 2
Allow custom content-type without setting a filename \fR\fR8cb9709\fP\fP
.PP
.SH "\fRv1\&.0\&.0-rc2\fP - 2015-07-21"
.PP
.SS "Merged"
.IP "\(bu" 2
#109 Append proper line break \fR\fR#123\fP\fP
.IP "\(bu" 2
Add shim for browser (browserify/webpack)\&. \fR\fR#122\fP\fP
.IP "\(bu" 2
Update license field \fR\fR#115\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Add shim for browser\&. \fR\fR87c33f4\fP\fP
.IP "\(bu" 2
Bump version \fR\fRa3f5d88\fP\fP
.PP
.SH "\fRv1\&.0\&.0-rc1\fP - 2015-06-13"
.PP
.SS "Merged"
.IP "\(bu" 2
v1\&.0\&.0-rc1 \fR\fR#114\fP\fP
.IP "\(bu" 2
Updated test targets \fR\fR#102\fP\fP
.IP "\(bu" 2
Remove duplicate plus sign \fR\fR#94\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Made https test local\&. Updated deps\&. \fR\fRafe1959\fP\fP
.IP "\(bu" 2
Proper self-signed ssl \fR\fR4d5ec50\fP\fP
.IP "\(bu" 2
Update HTTPS handling for modern days \fR\fR2c11b01\fP\fP
.IP "\(bu" 2
Made tests more local \fR\fR09633fa\fP\fP
.IP "\(bu" 2
Auto create tmp folder for Formidable \fR\fR28714b7\fP\fP
.IP "\(bu" 2
remove duplicate plus sign \fR\fR36e09c6\fP\fP
.PP
.SH "\fR0\&.2\fP - 2014-12-06"
.PP
.SS "Merged"
.IP "\(bu" 2
Bumped version \fR\fR#96\fP\fP
.IP "\(bu" 2
Replace mime library\&. \fR\fR#95\fP\fP
.IP "\(bu" 2
#71 Respect bytes range in a read stream\&. \fR\fR#73\fP\fP
.PP
.SH "\fR0\&.1\&.4\fP - 2014-06-23"
.PP
.SS "Merged"
.IP "\(bu" 2
Updated version\&. \fR\fR#76\fP\fP
.IP "\(bu" 2
#71 Respect bytes range in a read stream\&. \fR\fR#75\fP\fP
.PP
.SH "\fR0\&.1\&.3\fP - 2014-06-17"
.PP
.SS "Merged"
.IP "\(bu" 2
Updated versions\&. \fR\fR#69\fP\fP
.IP "\(bu" 2
Added custom headers support \fR\fR#60\fP\fP
.IP "\(bu" 2
Added test for Request\&. Small fixes\&. \fR\fR#56\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Added test for the custom header functionality \fR\fRbd50685\fP\fP
.IP "\(bu" 2
Documented custom headers option \fR\fR77a024a\fP\fP
.IP "\(bu" 2
Removed 0\&.6 support\&. \fR\fRaee8dce\fP\fP
.PP
.SH "\fR0\&.1\&.2\fP - 2013-10-02"
.PP
.SS "Merged"
.IP "\(bu" 2
Fixed default https port assignment, added tests\&. \fR\fR#52\fP\fP
.IP "\(bu" 2
#45 Added tests for multi-submit\&. Updated readme\&. \fR\fR#49\fP\fP
.IP "\(bu" 2
#47 return request from \&.submit() \fR\fR#48\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Bumped version\&. \fR\fR2b761b2\fP\fP
.PP
.SH "\fR0\&.1\&.1\fP - 2013-08-21"
.PP
.SS "Merged"
.IP "\(bu" 2
Added license type and reference to package\&.json \fR\fR#46\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
#47 return request from \&.submit() \fR\fR1d61c2d\fP\fP
.IP "\(bu" 2
#47 Updated readme\&. \fR\fRe3dae15\fP\fP
.PP
.SH "\fR0\&.1\&.0\fP - 2013-07-08"
.PP
.SS "Merged"
.IP "\(bu" 2
Update master to 0\&.1\&.0 \fR\fR#44\fP\fP
.IP "\(bu" 2
0\&.1\&.0 - Added error handling\&. Streamlined edge cases behavior\&. \fR\fR#43\fP\fP
.IP "\(bu" 2
Pointed badges back to mothership\&. \fR\fR#39\fP\fP
.IP "\(bu" 2
Updated node-fake to support 0\&.11 tests\&. \fR\fR#37\fP\fP
.IP "\(bu" 2
Updated tests to play nice with 0\&.10 \fR\fR#36\fP\fP
.IP "\(bu" 2
#32 Added \&.npmignore \fR\fR#34\fP\fP
.IP "\(bu" 2
Spring cleaning \fR\fR#30\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Added error handling\&. Streamlined edge cases behavior\&. \fR\fR4da496e\fP\fP
.IP "\(bu" 2
Made tests more deterministic\&. \fR\fR7fc009b\fP\fP
.IP "\(bu" 2
Fixed styling\&. \fR\fRd373b41\fP\fP
.IP "\(bu" 2
#40 Updated Readme\&.md regarding getLengthSync() \fR\fRefb373f\fP\fP
.IP "\(bu" 2
Updated readme\&. \fR\fR527e3a6\fP\fP
.PP
.SH "\fR0\&.0\&.10\fP - 2013-05-08"
.PP
.SS "Commits"
.IP "\(bu" 2
Updated tests to play nice with 0\&.10\&. \fR\fR932b39b\fP\fP
.IP "\(bu" 2
Added dependency tracking\&. \fR\fR3131d7f\fP\fP
.PP
.SH "0\&.0\&.9 - 2013-04-29"
.PP
.SS "Merged"
.IP "\(bu" 2
Custom params for form\&.submit() should cover most edge cases\&. \fR\fR#22\fP\fP
.IP "\(bu" 2
Updated Readme and version number\&. \fR\fR#20\fP\fP
.IP "\(bu" 2
Allow custom headers and pre-known length in parts \fR\fR#17\fP\fP
.IP "\(bu" 2
Bumped version number\&. \fR\fR#12\fP\fP
.IP "\(bu" 2
Fix for #10 \fR\fR#11\fP\fP
.IP "\(bu" 2
Bumped version number\&. \fR\fR#8\fP\fP
.IP "\(bu" 2
Added support for https destination, http-response and mikeal's request streams\&. \fR\fR#7\fP\fP
.IP "\(bu" 2
Updated git url\&. \fR\fR#6\fP\fP
.IP "\(bu" 2
Version bump\&. \fR\fR#5\fP\fP
.IP "\(bu" 2
Changes to support custom content-type and getLengthSync\&. \fR\fR#4\fP\fP
.IP "\(bu" 2
make \&.submit(url) use host from url, not 'localhost' \fR\fR#2\fP\fP
.IP "\(bu" 2
Make package\&.json JSON \fR\fR#1\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
Add MIT license \fR\fR#14\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Spring cleaning\&. \fR\fR850ba1b\fP\fP
.IP "\(bu" 2
Added custom request params to form\&.submit()\&. Made tests more stable\&. \fR\fRde3502f\fP\fP
.IP "\(bu" 2
Basic form (no files) working \fR\fR6ffdc34\fP\fP
.IP "\(bu" 2
Got initial test to pass \fR\fR9a59d08\fP\fP
.IP "\(bu" 2
Implement initial getLength \fR\fR9060c91\fP\fP
.IP "\(bu" 2
Make getLength work with file streams \fR\fR6f6b1e9\fP\fP
.IP "\(bu" 2
Implemented a simplistic submit() function \fR\fR41e9cc1\fP\fP
.IP "\(bu" 2
added test for custom headers and content-length in parts (felixge/node-form-data/17) \fR\fRb16d14e\fP\fP
.IP "\(bu" 2
Fixed code styling\&. \fR\fR5847424\fP\fP
.IP "\(bu" 2
#29 Added custom filename and content-type options to support identity-less streams\&. \fR\fRadf8b4a\fP\fP
.IP "\(bu" 2
Initial Readme and package\&.json \fR\fR8c744e5\fP\fP
.IP "\(bu" 2
allow append() to completely override header and boundary \fR\fR3fb2ad4\fP\fP
.IP "\(bu" 2
Syntax highlighting \fR\fRab3a6a5\fP\fP
.IP "\(bu" 2
Updated Readme\&.md \fR\fRde8f441\fP\fP
.IP "\(bu" 2
Added examples to Readme file\&. \fR\fRc406ac9\fP\fP
.IP "\(bu" 2
pass options\&.knownLength to set length at beginning, w/o waiting for async size calculation \fR\fRe2ac039\fP\fP
.IP "\(bu" 2
Updated dependencies and added test command\&. \fR\fR09bd7cd\fP\fP
.IP "\(bu" 2
Bumped version\&. Updated readme\&. \fR\fR4581140\fP\fP
.IP "\(bu" 2
Test runner \fR\fR1707ebb\fP\fP
.IP "\(bu" 2
Added \&.npmignore, bumped version\&. \fR\fR2e033e0\fP\fP
.IP "\(bu" 2
FormData\&.prototype\&.append takes and passes along options (for header) \fR\fRb519203\fP\fP
.IP "\(bu" 2
Make package\&.json JSON \fR\fRbf1b58d\fP\fP
.IP "\(bu" 2
Add dependencies to package\&.json \fR\fR7413d0b\fP\fP
.IP "\(bu" 2
Add convenient submit() interface \fR\fR55855e4\fP\fP
.IP "\(bu" 2
Fix content type \fR\fR08b6ae3\fP\fP
.IP "\(bu" 2
Combatting travis rvm calls\&. \fR\fR409adfd\fP\fP
.IP "\(bu" 2
Fixed Issue #2 \fR\fRb3a5d66\fP\fP
.IP "\(bu" 2
Fix for #10\&. \fR\fRbab70b9\fP\fP
.IP "\(bu" 2
Trying workarounds for formidable - 0\&.6 "love"\&. \fR\fR25782a3\fP\fP
.IP "\(bu" 2
change whitespace to conform with felixge's style guide \fR\fR9fa34f4\fP\fP
.IP "\(bu" 2
Add async to deps \fR\fRb7d1a6b\fP\fP
.IP "\(bu" 2
typo \fR\fR7860a9c\fP\fP
.IP "\(bu" 2
Bumped version\&. \fR\fRfa36c1b\fP\fP
.IP "\(bu" 2
Updated \&.gitignore \fR\fRde567bd\fP\fP
.IP "\(bu" 2
Don't rely on resume() being called by pipe \fR\fR1deae47\fP\fP
.IP "\(bu" 2
One more wrong content type \fR\fR28f166d\fP\fP
.IP "\(bu" 2
Another typo \fR\fRb959b6a\fP\fP
.IP "\(bu" 2
Typo \fR\fR698fa0a\fP\fP
.IP "\(bu" 2
Being simply dumb\&. \fR\fRb614db8\fP\fP
.IP "\(bu" 2
Fixed typo in the filename\&. \fR\fR30af6be\fP\fP 
.PP

