.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2math-intrinsics_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2math-intrinsics_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.1\&.0\fP - 2024-12-18"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRround\fP \fR\fR7cfb044\fP\fP
.IP "\(bu" 2
[Tests] add attw \fR\fRe96be8f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/tape\fP \fR\fR30d0023\fP\fP
.PP
.SH "v1\&.0\&.0 - 2024-12-11"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme, types \fR\fRb898caa\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR02745b0\fP\fP
.IP "\(bu" 2
[New] add \fRconstants/maxArrayLength\fP, \fRmod\fP \fR\fRb978178\fP\fP
.IP "\(bu" 2
npm init \fR\fRa39fc57\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR9451580\fP\fP 
.PP

