.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_photo_page_2_h_e_l_p" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_photo_page_2_h_e_l_p \- Getting Started 
.PP

.SS "Reference Documentation"
For further reference, please consider the following sections:

.PP
.IP "\(bu" 2
\fROfficial Apache Maven documentation\fP
.IP "\(bu" 2
\fRSpring Boot Maven Plugin Reference Guide\fP
.IP "\(bu" 2
\fRCreate an OCI image\fP
.IP "\(bu" 2
\fRSpring Boot DevTools\fP
.IP "\(bu" 2
\fRSpring Web\fP
.PP
.SS "Guides"
The following guides illustrate how to use some features concretely:

.PP
.IP "\(bu" 2
\fRBuilding a RESTful Web Service\fP
.IP "\(bu" 2
\fRServing Web Content with Spring MVC\fP
.IP "\(bu" 2
\fRBuilding REST services with Spring\fP
.PP
.SS "Maven Parent overrides"
Due to Maven's design, elements are inherited from the parent POM to the project POM\&. While most of the inheritance is fine, it also inherits unwanted elements like \fR<license>\fP and \fR<developers>\fP from the parent\&. To prevent this, the project POM contains empty overrides for these elements\&. If you manually switch to a different parent and actually want the inheritance, you need to remove those overrides\&. 
