.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2fast-glob_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2fast-glob_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g \- \fR5\&.1\&.2\fP (2021-03-06) 
.PP

.SS "Bug Fixes"
.IP "\(bu" 2
eliminate ReDoS (\fR#36\fP) (\fRf923116\fP)
.PP
.SS "\fR5\&.1\&.1\fP (2021-01-27)"
.SS "Bug Fixes"
.IP "\(bu" 2
unescape exclamation mark (\fR#26\fP) (\fRa98874f\fP)
.PP
.SH "\fR5\&.1\&.0\fP (2021-01-27)"
.PP
.SS "Features"
.IP "\(bu" 2
add \fRflipBackslashes\fP option to disable auto conversion of slashes (closes \fR#24\fP) (\fR#25\fP) (\fReecf91d\fP)
.PP
.SH "\fR5\&.0\&.0\fP (2021-01-27)"
.PP
.SS "⚠ BREAKING CHANGES"
.IP "\(bu" 2
Drop support for node <6 & bump dependencies
.PP
.SS "Miscellaneous Chores"
.IP "\(bu" 2
Drop support for node <6 & bump dependencies (\fR896c0c0\fP)
.PP
.SH "\fR4\&.0\&.0\fP (2021-01-27)"
.PP
.SS "⚠ BREAKING CHANGES"
.IP "\(bu" 2
question marks are valid path characters on Windows so avoid flagging as a glob when alone
.IP "\(bu" 2
Update is-glob dependency
.PP
.SS "Features"
.IP "\(bu" 2
hoist regexps and strings for performance gains (\fR4a80667\fP)
.IP "\(bu" 2
question marks are valid path characters on Windows so avoid flagging as a glob when alone (\fR2a551dd\fP)
.IP "\(bu" 2
Update is-glob dependency (\fRe41fcd8\fP)
.PP
.SH "\fR3\&.1\&.0\fP (2021-01-27)"
.PP
.SS "Features"
.IP "\(bu" 2
allow basic win32 backslash use (\fR272afa5\fP)
.IP "\(bu" 2
handle extglobs (parentheses) containing separators (\fR7db1bdb\fP)
.IP "\(bu" 2
new approach to braces/brackets handling (\fR8269bd8\fP)
.IP "\(bu" 2
pre-process braces/brackets sections (\fR9ef8a87\fP)
.IP "\(bu" 2
preserve escaped brace/bracket at end of string (\fR8cfb0ba\fP)
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
trailing escaped square brackets (\fR99ec9fe\fP)
.PP
.SS "\fR3\&.0\&.1\fP (2021-01-27)"
.SS "Features"
.IP "\(bu" 2
use path-dirname ponyfill (\fRcdbea5f\fP)
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
unescape glob-escaped dirnames on output (\fR598c533\fP)
.PP
.SH "\fR3\&.0\&.0\fP (2021-01-27)"
.PP
.SS "⚠ BREAKING CHANGES"
.IP "\(bu" 2
update is-glob dependency
.PP
.SS "Features"
.IP "\(bu" 2
update is-glob dependency (\fR5c5f8ef\fP)
.PP
.SH "\fR2\&.0\&.0\fP (2021-01-27)"
.PP
.SS "Features"
.IP "\(bu" 2
move up to dirname regardless of glob characters (\fRf97fb83\fP)
.PP
.SH "\fR1\&.3\&.0\fP (2021-01-27)"
.PP
.SH "\fR1\&.2\&.0\fP (2021-01-27)"
.PP
.SS "Reverts"
.IP "\(bu" 2
feat: make regex test strings smaller (\fRdc80fa9\fP)
.PP
.SH "\fR1\&.1\&.0\fP (2021-01-27)"
.PP
.SS "Features"
.IP "\(bu" 2
make regex test strings smaller (\fRcd83220\fP)
.PP
.SH "1\&.0\&.0 (2021-01-27)"
.PP

