.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2_0dhumanwhocodes_2module-importer_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2_0dhumanwhocodes_2module-importer_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP

.SH "\fR1\&.0\&.1\fP (2022-08-18)"
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Ensure CommonJS mode works correctly\&. (\fRcf54a0b\fP), closes \fR#6\fP
.PP
.SH "1\&.0\&.0 (2022-08-17)"
.PP
.SS "Features"
.IP "\(bu" 2
Implement ModuleImporter (\fR3ce4e82\fP) 
.PP

