.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2fastq_2_s_e_c_u_r_i_t_y" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2fastq_2_s_e_c_u_r_i_t_y \- Security Policy 
.PP

.SH "Supported Versions"
.PP
Use this section to tell people about which versions of your project are currently being supported with security updates\&.

.PP
Version  Supported  1\&.x  :white_check_mark:  < 1\&.0  :x:  
.SH "Reporting a Vulnerability"
.PP
Please report all vulnerabilities at \fRhttps://github\&.com/mcollina/fastq/security\fP\&. 
