.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2es-set-tostringtag_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2es-set-tostringtag_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv2\&.1\&.0\fP - 2025-01-01"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] split out node 10-20, and 20+ \fR\fRede033c\fP\fP
.IP "\(bu" 2
[types] use shared config \fR\fR28ef164\fP\fP
.IP "\(bu" 2
[New] add \fRnonConfigurable\fP option \fR\fR3bee3f0\fP\fP
.IP "\(bu" 2
[Fix] validate boolean option argument \fR\fR3c8a609\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@arethetypeswrong/cli\fP, \fR@ljharb/eslint-config\fP, \fR@ljharb/tsconfig\fP, \fR@types/get-intrinsic\fP, \fR@types/tape\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fR501a969\fP\fP
.IP "\(bu" 2
[Tests] add coverage \fR\fR18af289\fP\fP
.IP "\(bu" 2
[readme] document \fRforce\fP option \fR\fRbd446a1\fP\fP
.IP "\(bu" 2
[Tests] use \fR@arethetypeswrong/cli\fP \fR\fR7c2c2fa\fP\fP
.IP "\(bu" 2
[Tests] replace \fRaud\fP with \fRnpm audit\fP \fR\fR9e372d7\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR7df1216\fP\fP
.IP "\(bu" 2
[Deps] update \fRhasown\fP \fR\fR993a7d2\fP\fP
.IP "\(bu" 2
[Dev Deps] add missing peer dep \fR\fR148ed8d\fP\fP
.PP
.SH "\fRv2\&.0\&.3\fP - 2024-02-20"
.PP
.SS "Commits"
.IP "\(bu" 2
add types \fR\fRd538513\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP, \fRhas-tostringtag\fP, \fRhasown\fP \fR\fRd129b29\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRnpmignore\fP, \fRtape\fP \fR\fR132ed23\fP\fP
.IP "\(bu" 2
[Tests] fix hasOwn require \fR\fRf89c831\fP\fP
.PP
.SH "\fRv2\&.0\&.2\fP - 2023-10-20"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRhasown\fP instead of \fRhas\fP \fR\fR0cc6c4e\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR70e447c\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR826aab7\fP\fP
.PP
.SH "\fRv2\&.0\&.1\fP - 2023-01-05"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] move \fRhas\fP to prod deps \fR\fR#2\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP \fR\fRb9eecd2\fP\fP
.PP
.SH "\fRv2\&.0\&.0\fP - 2022-12-21"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] refactor tests \fR\fR168dcfb\fP\fP
.IP "\(bu" 2
[Breaking] do not set toStringTag if it is already set \fR\fR226ab87\fP\fP
.IP "\(bu" 2
[New] add \fRforce\fP option to set even if already set \fR\fR1abd4ec\fP\fP
.PP
.SH "v1\&.0\&.0 - 2022-12-21"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme \fR\fRa0e1147\fP\fP
.IP "\(bu" 2
Initial commit \fR\fRffd4aff\fP\fP
.IP "\(bu" 2
npm init \fR\fRfffe5bd\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRd363871\fP\fP 
.PP

