.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2optionator_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2optionator_2_c_h_a_n_g_e_l_o_g \- 0\&.9\&.0 
.PP


.PP
.IP "\(bu" 2
update dependencies, in particular \fRlevn\fP and \fRtype-check\fP - this could affect behaviour of argument parsing
.PP
.SH "0\&.8\&.3"
.PP
.IP "\(bu" 2
changes dependency from \fRwordwrap\fP to \fRword-wrap\fP due to license issue
.IP "\(bu" 2
update dependencies
.PP
.SH "0\&.8\&.2"
.PP
.IP "\(bu" 2
fix bug #18 - detect missing value when flag is last item
.IP "\(bu" 2
update dependencies
.PP
.SH "0\&.8\&.1"
.PP
.IP "\(bu" 2
update \fRfast-levenshtein\fP dependency
.PP
.SH "0\&.8\&.0"
.PP
.IP "\(bu" 2
update \fRlevn\fP dependency - supplying a float value to an option with type \fRInt\fP now throws an error, instead of silently converting to an \fRInt\fP
.PP
.SH "0\&.7\&.1"
.PP
.IP "\(bu" 2
fix bug with use of \fRdefaults\fP and \fRconcatRepeatedArrays\fP or \fRmergeRepeatedObjects\fP
.PP
.SH "0\&.7\&.0"
.PP
.IP "\(bu" 2
added \fRconcatrepeatedarrays\fP option: \fRoneValuePerFlag\fP, only allows one array value per flag
.IP "\(bu" 2
added \fRtypeAliases\fP option
.IP "\(bu" 2
added \fRparseArgv\fP which takes an array and parses with the first two items sliced off
.IP "\(bu" 2
changed enum help style
.IP "\(bu" 2
bug fixes (#12)
.IP "\(bu" 2
use of \fRconcatRepeatedArrays\fP and \fRmergeRepeatedObjects\fP at the top level is deprecated, use it as either a per-option option, or set them in the \fRdefaults\fP object to set them for all objects
.PP
.SH "0\&.6\&.0"
.PP
.IP "\(bu" 2
added \fRdefaults\fP lib-option flag, allowing one to set default properties for all options
.IP "\(bu" 2
added \fRconcatRepeatedArrays\fP and \fRmergeRepeatedObjects\fP as option level properties, allowing you to turn this feature on for specific options only
.PP
.SH "0\&.5\&.0"
.PP
.IP "\(bu" 2
\fRBoolean\fP flags with \fRdefault: 'true'\fP, and no short aliases, will by default show the \fR--no\fP version in help
.PP
.SH "0\&.4\&.0"
.PP
.IP "\(bu" 2
add \fRmergeRepeatedObjects\fP setting
.PP
.SH "0\&.3\&.0"
.PP
.IP "\(bu" 2
add \fRconcatRepeatedArrays\fP setting
.IP "\(bu" 2
add \fRoverrideRequired\fP option setting
.IP "\(bu" 2
use just Levenshtein string compare algo rather than Levenshtein Damerau to due dependency license issue
.PP
.SH "0\&.2\&.2"
.PP
.IP "\(bu" 2
bug fixes
.PP
.SH "0\&.2\&.1"
.PP
.IP "\(bu" 2
improved interpolation
.IP "\(bu" 2
added changelog
.PP
.SH "0\&.2\&.0"
.PP
.IP "\(bu" 2
add dependency checks to options - added \fRdependsOn\fP as an option property
.IP "\(bu" 2
add interpolation for \fRprepend\fP and \fRappend\fP text with new \fRgenerateHelp\fP option, \fRinterpolate\fP
.PP
.SH "0\&.1\&.1"
.PP
.IP "\(bu" 2
update dependencies
.PP
.SH "0\&.1\&.0"
.PP
.IP "\(bu" 2
initial release 
.PP

