.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2_0dbabel_2parser_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2_0dbabel_2parser_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
.RS 4
\fBTags:\fP
.IP "\(bu" 2
:boom: [Breaking Change]
.IP "\(bu" 2
:eyeglasses: [Spec Compliance]
.IP "\(bu" 2
:rocket: [New Feature]
.IP "\(bu" 2
:bug: [Bug Fix]
.IP "\(bu" 2
:memo: [Documentation]
.IP "\(bu" 2
:house: [Internal]
.IP "\(bu" 2
:nail_care: [Polish] 
.PP
.RE
.PP

.PP
.RS 4
Semver Policy: https://github.com/babel/babel/tree/main/packages/babel-parser#semver 
.RE
.PP

.PP
\fINote: Gaps between patch versions are faulty, broken or test releases\&.\fP

.PP
See the \fRBabel Changelog\fP for the pre-6\&.8\&.0 version Changelog\&.
.SH "6\&.17\&.1 (2017-05-10)"
.PP
.SS ":bug: Bug Fix"
.IP "\(bu" 2
Fix typo in flow spread operator error (Brian Ng)
.IP "\(bu" 2
Fixed invalid number literal parsing (\fR#473\fP) (Alex Kuzmenko)
.IP "\(bu" 2
Fix number parser (\fR#433\fP) (Alex Kuzmenko)
.IP "\(bu" 2
Ensure non pattern shorthand props are checked for reserved words (\fR#479\fP) (Brian Ng)
.IP "\(bu" 2
Remove jsx context when parsing arrow functions (\fR#475\fP) (Brian Ng)
.IP "\(bu" 2
Allow super in class properties (\fR#499\fP) (Brian Ng)
.IP "\(bu" 2
Allow flow class field to be named constructor (\fR#510\fP) (Brian Ng)
.PP
.SH "6\&.17\&.0 (2017-04-20)"
.PP
.SS ":bug: Bug Fix"
.IP "\(bu" 2
Cherry-pick #418 to 6\&.x (\fR#476\fP) (Sebastian McKenzie)
.IP "\(bu" 2
Add support for invalid escapes in tagged templates (\fR#274\fP) (Kevin Gibbons)
.IP "\(bu" 2
Throw error if new\&.target is used outside of a function (\fR#402\fP) (Brian Ng)
.IP "\(bu" 2
Fix parsing of class properties (\fR#351\fP) (Kevin Gibbons)
.IP "\(bu" 2
Fix parsing yield with dynamicImport (\fR#383\fP) (Brian Ng)
.IP "\(bu" 2
Ensure consistent start args for parseParenItem (\fR#386\fP) (Brian Ng)
.PP
.SH "7\&.0\&.0-beta\&.8 (2017-04-04)"
.PP
.SS "New Feature"
.IP "\(bu" 2
Add support for flow type spread (#418) (Conrad Buck)
.IP "\(bu" 2
Allow statics in flow interfaces (#427) (Brian Ng)
.PP
.SS "Bug Fix"
.IP "\(bu" 2
Fix predicate attachment to match flow parser (#428) (Brian Ng)
.IP "\(bu" 2
Add extra\&.raw back to JSXText and JSXAttribute (#344) (Alex Rattray)
.IP "\(bu" 2
Fix rest parameters with array and objects (#424) (Brian Ng)
.IP "\(bu" 2
Fix number parser (#433) (Alex Kuzmenko)
.PP
.SS "Docs"
.IP "\(bu" 2
Fix CONTRIBUTING\&.md [skip ci] (#432) (Alex Kuzmenko)
.PP
.SS "Internal"
.IP "\(bu" 2
Use babel-register script when running babel smoke tests (#442) (Brian Ng)
.PP
.SH "7\&.0\&.0-beta\&.7 (2017-03-22)"
.PP
.SS "Spec Compliance"
.IP "\(bu" 2
Remove babylon plugin for template revision since it's stage-4 (#426) (Henry Zhu)
.PP
.SS "Bug Fix"
.IP "\(bu" 2
Fix push-pop logic in flow (#405) (Daniel Tschinder)
.PP
.SH "7\&.0\&.0-beta\&.6 (2017-03-21)"
.PP
.SS "New Feature"
.IP "\(bu" 2
Add support for invalid escapes in tagged templates (#274) (Kevin Gibbons)
.PP
.SS "Polish"
.IP "\(bu" 2
Improves error message when super is called outside of constructor (#408) (Arshabh Kumar Agarwal)
.PP
.SS "Docs"
.IP "\(bu" 2
[7\&.0] Moved value field in spec from ObjectMember to ObjectProperty as ObjectMethod's don't have it (#415) [skip ci] (James Browning)
.PP
.SH "7\&.0\&.0-beta\&.5 (2017-03-21)"
.PP
.SS "Bug Fix"
.IP "\(bu" 2
Throw error if new\&.target is used outside of a function (#402) (Brian Ng)
.IP "\(bu" 2
Fix parsing of class properties (#351) (Kevin Gibbons)
.PP
.SS "Other"
.IP "\(bu" 2
Test runner: Detect extra property in 'actual' but not in 'expected'\&. (#407) (Andy)
.IP "\(bu" 2
Optimize travis builds (#419) (Daniel Tschinder)
.IP "\(bu" 2
Update codecov to 2\&.0 (#412) (Daniel Tschinder)
.IP "\(bu" 2
Fix spec for ClassMethod: It doesn't have a function, it \fIis\fP a function\&. (#406) [skip ci] (Andy)
.IP "\(bu" 2
Changed Non-existent RestPattern to RestElement which is what is actually parsed (#409) [skip ci] (James Browning)
.IP "\(bu" 2
Upgrade flow to 0\&.41 (Daniel Tschinder)
.IP "\(bu" 2
Fix watch command (#403) (Brian Ng)
.IP "\(bu" 2
Update yarn lock (Daniel Tschinder)
.IP "\(bu" 2
Fix watch command (#403) (Brian Ng)
.IP "\(bu" 2
chore(package): update flow-bin to version 0\&.41\&.0 (#395) (greenkeeper[bot])
.IP "\(bu" 2
Add estree test for correct order of directives (Daniel Tschinder)
.IP "\(bu" 2
Add DoExpression to spec (#364) (Alex Kuzmenko)
.IP "\(bu" 2
Mention cloning of repository in CONTRIBUTING\&.md (#391) [skip ci] (Sumedh Nimkarde)
.IP "\(bu" 2
Explain how to run only one test (#389) [skip ci] (Aaron Ang)
.PP
.SH "7\&.0\&.0-beta\&.4 (2017-03-01)"
.PP
.IP "\(bu" 2
Don't consume async when checking for async func decl (#377) (Brian Ng)
.IP "\(bu" 2
add \fRranges\fP option [skip ci] (Henry Zhu)
.IP "\(bu" 2
Don't parse class properties without initializers when classProperties is disabled and Flow is enabled (#300) (Andrew Levine)
.PP
.SH "7\&.0\&.0-beta\&.3 (2017-02-28)"
.PP
.IP "\(bu" 2
[7\&.0] Change RestProperty/SpreadProperty to RestElement/SpreadElement (#384)
.IP "\(bu" 2
Merge changes from 6\&.x
.PP
.SH "7\&.0\&.0-beta\&.2 (2017-02-20)"
.PP
.IP "\(bu" 2
estree: correctly change literals in all cases (#368) (Daniel Tschinder)
.PP
.SH "7\&.0\&.0-beta\&.1 (2017-02-20)"
.PP
.IP "\(bu" 2
Fix negative number literal typeannotations (#366) (Daniel Tschinder)
.IP "\(bu" 2
Update contributing with more test info [skip ci] (#355) (Brian Ng)
.PP
.SH "7\&.0\&.0-beta\&.0 (2017-02-15)"
.PP
.IP "\(bu" 2
Reintroduce Variance node (#333) (Daniel Tschinder)
.IP "\(bu" 2
Rename NumericLiteralTypeAnnotation to NumberLiteralTypeAnnotation (#332) (Charles Pick)
.IP "\(bu" 2
[7\&.0] Remove ForAwaitStatement, add await flag to ForOfStatement (#349) (Brandon Dail)
.IP "\(bu" 2
chore(package): update ava to version 0\&.18\&.0 (#345) (greenkeeper[bot])
.IP "\(bu" 2
chore(package): update babel-plugin-istanbul to version 4\&.0\&.0 (#350) (greenkeeper[bot])
.IP "\(bu" 2
Change location of ObjectTypeIndexer to match flow (#228) (Daniel Tschinder)
.IP "\(bu" 2
Rename flow AST Type ExistentialTypeParam to ExistsTypeAnnotation (#322) (Toru Kobayashi)
.IP "\(bu" 2
Revert "Temporary rollback for erroring on trailing comma with spread (#154)" (#290) (Daniel Tschinder)
.IP "\(bu" 2
Remove classConstructorCall plugin (#291) (Brian Ng)
.IP "\(bu" 2
Update yarn\&.lock (Daniel Tschinder)
.IP "\(bu" 2
Update cross-env to 3\&.x (Daniel Tschinder)
.IP "\(bu" 2
[7\&.0] Remove node 0\&.10, 0\&.12 and 5 from Travis (#284) (Sergey Rubanov)
.IP "\(bu" 2
Remove \fRString\&.fromCodePoint\fP shim (#279) (Mathias Bynens)
.PP
.SH "6\&.16\&.1 (2017-02-23)"
.PP
.SS ":bug: Regression"
.IP "\(bu" 2
Revert "Fix export default async function to be FunctionDeclaration" (\fR#375\fP)
.PP

.PP
Need to modify Babel for this AST node change, so moving to 7\&.0\&.

.PP
.IP "\(bu" 2
Revert "Don't parse class properties without initializers when classProperties plugin is disabled, and Flow is enabled" (\fR#376\fP)
.PP

.PP
\fRreact-native\fP broke with this so we reverted\&.
.SH "6\&.16\&.0 (2017-02-23)"
.PP
.SS ":rocket: New Feature"
\fI\fBESTree\fP\fP compatibility as plugin (\fR#277\fP) (Daniel Tschinder)

.PP
We finally introduce a new compatibility layer for ESTree\&. To put babylon into ESTree-compatible mode the new plugin \fRestree\fP can be enabled\&. In this mode the parser will output an AST that is compliant to the specs of \fRESTree\fP

.PP
We highly recommend everyone who uses babylon outside of babel to use this plugin\&. This will make it much easier for users to switch between different ESTree-compatible parsers\&. We so far tested several projects with different parsers and exchanged their parser to babylon and in nearly all cases it worked out of the box\&. Some other estree-compatible parsers include \fRacorn\fP, \fResprima\fP, \fRespree\fP, \fRflow-parser\fP, etc\&.

.PP
To enable \fRestree\fP mode simply add the plugin in the config: 
.PP
.nf
{
  "plugins": [ "estree" ]
}

.fi
.PP

.PP
If you want to migrate your project from non-ESTree mode to ESTree, have a look at our \fRReadme\fP, where all deviations are mentioned\&.

.PP
Add a parseExpression public method (\fR#213\fP) (jeromew)

.PP
Babylon exports a new function to parse a single expression

.PP
.PP
.nf
import { parseExpression } from 'babylon';

const ast = parseExpression('x || y && z', options);
.fi
.PP

.PP
The returned AST will only consist of the expression\&. The options are the same as for \fRparse()\fP

.PP
Add startLine option (\fR#346\fP) (Raphael Mu)

.PP
A new option was added to babylon allowing to change the initial linenumber for the first line which is usually \fR1\fP\&. Changing this for example to \fR100\fP will make line \fR1\fP of the input source to be marked as line \fR100\fP, line \fR2\fP as \fR101\fP, line \fR3\fP as \fR102\fP, \&.\&.\&.

.PP
Function predicate declaration (\fR#103\fP) (Panagiotis Vekris)

.PP
Added support for function predicates which flow introduced in version 0\&.33\&.0

.PP
.PP
.nf
declare function is_number(x: mixed): boolean %checks(typeof x === "number");
.fi
.PP

.PP
Allow imports in declare module (\fR#315\fP) (Daniel Tschinder)

.PP
Added support for imports within module declarations which flow introduced in version 0\&.37\&.0

.PP
.PP
.nf
declare module "C" {
  import type { DT } from "D";
  declare export type CT = { D: DT };
}
.fi
.PP
.SS ":eyeglasses: Spec Compliance"
Forbid semicolons after decorators in classes (\fR#352\fP) (Kevin Gibbons)

.PP
This example now correctly throws an error when there is a semicolon after the decorator:

.PP
.PP
.nf
class A {
@a;
foo(){}
}
.fi
.PP

.PP
Keywords are not allowed as local specifier (\fR#307\fP) (Daniel Tschinder)

.PP
Using keywords in imports is not allowed anymore:

.PP
.PP
.nf
import { default } from "foo";
import { a as debugger } from "foo";
.fi
.PP

.PP
Do not allow overwritting of primitive types (\fR#314\fP) (Daniel Tschinder)

.PP
In flow it is now forbidden to overwrite the primitive types \fR"any"\fP, \fR"mixed"\fP, \fR"empty"\fP, \fR"bool"\fP, \fR"boolean"\fP, \fR"number"\fP, \fR"string"\fP, \fR"void"\fP and \fR"null"\fP with your own type declaration\&.

.PP
Disallow import type { type a } from … (\fR#305\fP) (Daniel Tschinder)

.PP
The following code now correctly throws an error

.PP
.PP
.nf
import type { type a } from "foo";
.fi
.PP

.PP
Don't parse class properties without initializers when classProperties is disabled and Flow is enabled (\fR#300\fP) (Andrew Levine)

.PP
Ensure that you enable the \fRclassProperties\fP plugin in order to enable correct parsing of class properties\&. Prior to this version it was possible to parse them by enabling the \fRflow\fP plugin but this was not intended the behaviour\&.

.PP
If you enable the flow plugin you can only define the type of the class properties, but not initialize them\&.

.PP
Fix export default async function to be FunctionDeclaration (\fR#324\fP) (Daniel Tschinder)

.PP
Parsing the following code now returns a \fRFunctionDeclaration\fP AST node instead of \fRFunctionExpression\fP\&.

.PP
.PP
.nf
export default async function bar() {};
.fi
.PP
.SS ":nail_care: Polish"
Improve error message on attempt to destructure named import (\fR#288\fP) (Brian Ng)
.SS ":bug: Bug Fix"
Fix negative number literal typeannotations (\fR#366\fP) (Daniel Tschinder)

.PP
Ensure takeDecorators is called on exported class (\fR#358\fP) (Brian Ng)

.PP
ESTree: correctly change literals in all cases (\fR#368\fP) (Daniel Tschinder)

.PP
Correctly convert RestProperty to Assignable (\fR#339\fP) (Daniel Tschinder)

.PP
Fix #321 by allowing question marks in type params (\fR#338\fP) (Daniel Tschinder)

.PP
Fix #336 by correctly setting arrow-param (\fR#337\fP) (Daniel Tschinder)

.PP
Fix parse error when destructuring \fRset\fP with default value (\fR#317\fP) (Brian Ng)

.PP
Fix ObjectTypeCallProperty static (\fR#298\fP) (Dan Harper)
.SS ":house: Internal"
Fix generator-method-with-computed-name spec (\fR#360\fP) (Alex Rattray)

.PP
Fix flow type-parameter-declaration test with unintended semantic (\fR#361\fP) (Alex Rattray)

.PP
Cleanup and splitup parser functions (\fR#295\fP) (Daniel Tschinder)

.PP
chore(package): update flow-bin to version 0\&.38\&.0 (\fR#313\fP) (greenkeeper[bot])

.PP
Call inner function instead of 1:1 copy to plugin (\fR#294\fP) (Daniel Tschinder)

.PP
Update eslint-config-babel to the latest version 🚀 (\fR#299\fP) (greenkeeper[bot])

.PP
Update eslint-config-babel to the latest version 🚀 (\fR#293\fP) (greenkeeper[bot])

.PP
devDeps: remove eslint-plugin-babel (\fR#292\fP) (Kai Cataldo)

.PP
Correct indent eslint rule config (\fR#276\fP) (Daniel Tschinder)

.PP
Fail tests that have expected\&.json and throws-option (\fR#285\fP) (Daniel Tschinder)
.SS ":memo: Documentation"
Update contributing with more test info [skip ci] (\fR#355\fP) (Brian Ng)

.PP
Update API documentation (\fR#330\fP) (Timothy Gu)

.PP
Added keywords to package\&.json (\fR#323\fP) (Dmytro)

.PP
AST spec: fix casing of \fRRegExpLiteral\fP (\fR#318\fP) (Mathias Bynens)
.SH "6\&.15\&.0 (2017-01-10)"
.PP
.SS ":eyeglasses: Spec Compliance"
Add support for Flow shorthand import type (\fR#267\fP) (Jeff Morrison)

.PP
This change implements flows new shorthand import syntax and where previously you had to write this code:

.PP
.PP
.nf
import {someValue} from "blah";
import type {someType} from "blah";
import typeof {someOtherValue} from "blah";
.fi
.PP

.PP
you can now write it like this:

.PP
.PP
.nf
import {
  someValue,
  type someType,
  typeof someOtherValue,
} from "blah";
.fi
.PP

.PP
For more information look at \fRthis\fP pull request\&.

.PP
flow: allow leading pipes in all positions (\fR#256\fP) (Vladimir Kurchatkin)

.PP
This change now allows a leading pipe everywhere types can be used: 
.PP
.nf
var f = (x): | 1 | 2 => 1;

.fi
.PP

.PP
Throw error when exporting non-declaration (\fR#241\fP) (Kai Cataldo)

.PP
Previously babylon parsed the following exports, although they are not valid: 
.PP
.nf
export typeof foo;
export new Foo();
export function() {};
export for (;;);
export while(foo);

.fi
.PP
.SS ":bug: Bug Fix"
Don't set inType flag when parsing property names (\fR#266\fP) (Vladimir Kurchatkin)

.PP
This fixes parsing of this case:

.PP
.PP
.nf
const map = {
  [age <= 17] : 'Too young'
};
.fi
.PP

.PP
Fix source location for JSXEmptyExpression nodes (fixes #248) (\fR#249\fP) (James Long)

.PP
The following case produced an invalid AST 
.PP
.nf
<div>{/* foo */}</div>

.fi
.PP

.PP
Use fromCodePoint to convert high value unicode entities (\fR#243\fP) (Ryan Duffy)

.PP
When high value unicode entities (e\&.g\&. 💩) were used in the input source code they are now correctly encoded in the resulting AST\&.

.PP
Rename folder to avoid Windows-illegal characters (\fR#281\fP) (Ryan Plant)

.PP
Allow this\&.state\&.clone() when parsing decorators (\fR#262\fP) (Alex Rattray)
.SS ":house: Internal"
User external-helpers (\fR#254\fP) (Daniel Tschinder)

.PP
Add watch script for dev (\fR#234\fP) (Kai Cataldo)

.PP
Freeze current plugins list for "*" option, and remove from README\&.md (\fR#245\fP) (Andrew Levine)

.PP
Prepare tests for multiple fixture runners\&. (\fR#240\fP) (Daniel Tschinder)

.PP
Add some test coverage for decorators stage-0 plugin (\fR#250\fP) (Andrew Levine)

.PP
Refactor tokenizer types file (\fR#263\fP) (Sven SAULEAU)

.PP
Update eslint-config-babel to the latest version 🚀 (\fR#273\fP) (greenkeeper[bot])

.PP
chore(package): update rollup to version 0\&.41\&.0 (\fR#272\fP) (greenkeeper[bot])

.PP
chore(package): update flow-bin to version 0\&.37\&.0 (\fR#255\fP) (greenkeeper[bot])
.SH "6\&.14\&.1 (2016-11-17)"
.PP
.SS ":bug: Bug Fix"
Allow \fR"plugins": ["*"]\fP (\fR#229\fP) (Daniel Tschinder)

.PP
.PP
.nf
{
  "plugins": ["*"]
}
.fi
.PP

.PP
Will include all parser plugins instead of specifying each one individually\&. Useful for tools like babel-eslint, jscodeshift, and ast-explorer\&.
.SH "6\&.14\&.0 (2016-11-16)"
.PP
.SS ":eyeglasses: Spec Compliance"
Throw error for reserved words \fRenum\fP and \fRawait\fP (\fR#195\fP) (Kai Cataldo)

.PP
\fR11\&.6\&.2\&.2 Future Reserved Words\fP

.PP
Babylon will throw for more reserved words such as \fRenum\fP or \fRawait\fP (in strict mode)\&.

.PP
.PP
.nf
class enum {} // throws
class await {} // throws in strict mode (module)
.fi
.PP

.PP
Optional names for function types and object type indexers (\fR#197\fP) (Gabe Levi)

.PP
So where you used to have to write

.PP
.PP
.nf
type A = (x: string, y: boolean) => number;
type B = (z: string) => number;
type C = { [key: string]: number };
.fi
.PP

.PP
you can now write (with flow 0\&.34\&.0)

.PP
.PP
.nf
type A = (string, boolean) => number;
type B = string => number;
type C = { [string]: number };
.fi
.PP

.PP
Parse flow nested array type annotations like \fRnumber[][]\fP (\fR#219\fP) (Bernhard Häussner)

.PP
Supports these form now of specifying array types:

.PP
.PP
.nf
var a: number[][][][];
var b: string[][];
.fi
.PP
.SS ":bug: Bug Fix"
Correctly eat semicolon at the end of \fRDelcareModuleExports\fP (\fR#223\fP) (Daniel Tschinder)

.PP
.PP
.nf
declare module "foo" { declare module\&.exports: number }
declare module "foo" { declare module\&.exports: number; }  // also allowed now
.fi
.PP
.SS ":house: Internal"
.IP "\(bu" 2
Count Babel tests towards Babylon code coverage (\fR#182\fP) (Moti Zilberman)
.IP "\(bu" 2
Fix strange line endings (\fR#214\fP) (Thomas Grainger)
.IP "\(bu" 2
Add node 7 (Daniel Tschinder)
.IP "\(bu" 2
chore(package): update flow-bin to version 0\&.34\&.0 (\fR#204\fP) (Greenkeeper)
.PP
.SH "v6\&.13\&.1 (2016-10-26)"
.PP
.SS ":nail_care: Polish"
.IP "\(bu" 2
Use rollup for bundling to speed up startup time (\fR#190\fP) (\fR@drewml\fP)
.PP

.PP
.PP
.nf
const babylon = require('babylon');
const ast = babylon\&.parse('var foo = "lol";');
.fi
.PP

.PP
With that test case, there was a ~95ms savings by removing the need for node to build/traverse the dependency graph\&.

.PP
\fBWithout bundling\fP 

.PP
\fBWith bundling\fP 

.PP
.IP "\(bu" 2
add clean command [skip ci] (\fR#201\fP) (Henry Zhu)
.IP "\(bu" 2
add ForAwaitStatement (async generator already added) [skip ci] (\fR#196\fP) (Henry Zhu)
.PP
.SH "v6\&.13\&.0 (2016-10-21)"
.PP
.SS ":eyeglasses: Spec Compliance"
Property variance type annotations for Flow plugin (\fR#161\fP) (Sam Goldman)

.PP
.RS 4
See https://flowtype.org/docs/variance.html for more information 
.RE
.PP

.PP
.PP
.nf
type T = { +p: T };
interface T { \-p: T };
declare class T { +[k:K]: V };
class T { \-[k:K]: V };
class C2 { +p: T = e };
.fi
.PP

.PP
Raise error on duplicate definition of \fBproto\fP (\fR#183\fP) (Moti Zilberman)

.PP
.PP
.nf
({ __proto__: 1, __proto__: 2 }) // Throws an error now
.fi
.PP
.SS ":bug: Bug Fix"
Flow: Allow class properties to be named \fRstatic\fP (\fR#184\fP) (Moti Zilberman)

.PP
.PP
.nf
declare class A {
  static: T;
}
.fi
.PP

.PP
Allow "async" as identifier for object literal property shorthand (\fR#187\fP) (Andrew Levine)

.PP
.PP
.nf
var foo = { async, bar };
.fi
.PP
.SS ":nail_care: Polish"
Fix flowtype and add inType to state (\fR#189\fP) (Daniel Tschinder)

.PP
.RS 4
This improves the performance slightly (because of hidden classes) 
.RE
.PP
.SS ":house: Internal"
Fix \&.gitattributes line ending setting (\fR#191\fP) (Moti Zilberman)

.PP
Increase test coverage (\fR#175\fP (Moti Zilberman)

.PP
Readd missin \&.eslinignore for IDEs (Daniel Tschinder)

.PP
Error on missing expected\&.json fixture in CI (\fR#188\fP) (Moti Zilberman)

.PP
Add \&.gitattributes and \&.editorconfig for LF line endings (\fR#179\fP) (Moti Zilberman)

.PP
Fixes two tests that are failing after the merge of #172 (\fR#177\fP) (Moti Zilberman)
.SH "v6\&.12\&.0 (2016-10-14)"
.PP
.SS ":eyeglasses: Spec Compliance"
Implement import() syntax (\fR#163\fP) (Jordan Gensler)
.SS "Dynamic Import"
.IP "\(bu" 2
Proposal Repo: https://github.com/domenic/proposal-dynamic-import
.IP "\(bu" 2
Championed by \fR@domenic\fP
.IP "\(bu" 2
stage-2
.IP "\(bu" 2
\fRsept-28 tc39 notes\fP
.PP

.PP
.RS 4
This repository contains a proposal for adding a "function-like" import() module loading syntactic form to JavaScript 
.RE
.PP

.PP
.PP
.nf
import(`\&./section\-modules/${link\&.dataset\&.entryModule}\&.js`)
\&.then(module => {
  module\&.loadPageInto(main);
})
.fi
.PP

.PP
Add EmptyTypeAnnotation (\fR#171\fP) (Sam Goldman)
.SS "EmptyTypeAnnotation"
Just wasn't covered before\&.

.PP
.PP
.nf
type T = empty;
.fi
.PP
.SS ":bug: Bug Fix"
Fix crash when exporting with destructuring and sparse array (\fR#170\fP) (Jeroen Engels)

.PP
.PP
.nf
// was failing due to sparse array
export const { foo: [ ,, qux7 ] } = bar;
.fi
.PP

.PP
Allow keyword in Flow object declaration property names with type parameters (\fR#146\fP) (Dan Harper)

.PP
.PP
.nf
declare class X {
  foobar<T>(): void;
  static foobar<T>(): void;
}
.fi
.PP

.PP
Allow keyword in object/class property names with Flow type parameters (\fR#145\fP) (Dan Harper)

.PP
.PP
.nf
class Foo {
  delete<T>(item: T): T {
    return item;
  }
}
.fi
.PP

.PP
Allow typeAnnotations for yield expressions (\fR#174\fP)) (Daniel Tschinder)

.PP
.PP
.nf
function *foo() {
  const x = (yield 5: any);
}
.fi
.PP
.SS ":nail_care: Polish"
Annotate more errors with expected token (\fR#172\fP)) (Moti Zilberman)

.PP
.PP
.nf
// Unexpected token, expected ; (1:6)
{ set 1 }
.fi
.PP
.SS ":house: Internal"
Remove kcheck (\fR#173\fP)) (Daniel Tschinder)

.PP
Also run flow, linting, babel tests on separate instances (add back node 0\&.10)
.SH "v6\&.11\&.6 (2016-10-12)"
.PP
.SS ":bug: Bug Fix/Regression"
Fix crash when exporting with destructuring and sparse array (\fR#170\fP) (Jeroen Engels)

.PP
.PP
.nf
// was failing with `Cannot read property 'type' of null` because of null identifiers
export const { foo: [ ,, qux7 ] } = bar;
.fi
.PP
.SH "v6\&.11\&.5 (2016-10-12)"
.PP
.SS ":eyeglasses: Spec Compliance"
Fix: Check for duplicate named exports in exported destructuring assignments (\fR#144\fP) (Kai Cataldo)

.PP
.PP
.nf
// `foo` has already been exported\&. Exported identifiers must be unique\&. (2:20)
export function foo() {};
export const { a: [{foo}] } = bar;
.fi
.PP

.PP
Fix: Check for duplicate named exports in exported rest elements/properties (\fR#164\fP) (Kai Cataldo)

.PP
.PP
.nf
// `foo` has already been exported\&. Exported identifiers must be unique\&. (2:22)
export const foo = 1;
export const [bar, \&.\&.\&.foo] = baz;
.fi
.PP
.SS ":bug: Bug Fix"
Fix: Allow identifier \fRasync\fP for default param in arrow expression (\fR#165\fP) (Kai Cataldo)

.PP
.PP
.nf
// this is ok now
const test = ({async = true}) => {};
.fi
.PP
.SS ":nail_care: Polish"
Babylon will now print out the token it's expecting if there's a \fRSyntaxError\fP (\fR#150\fP) (Daniel Tschinder)

.PP
.PP
.nf
# So in the case of a missing ending curly (`}`)
Module build failed: SyntaxError: Unexpected token, expected } (30:0)
  28 |   }
  29 |
> 30 |
     | ^
.fi
.PP
.SH "v6\&.11\&.4 (2016-10-03)"
.PP
Temporary rollback for erroring on trailing comma with spread (#154) (Henry Zhu)
.SH "v6\&.11\&.3 (2016-10-01)"
.PP
.SS ":eyeglasses: Spec Compliance"
Add static errors for object rest (#149) (\fR@danez\fP)

.PP
.RS 4
https://github.com/sebmarkbage/ecmascript-rest-spread 
.RE
.PP

.PP
Object rest copies the \fIrest\fP of properties from the right hand side \fRobj\fP starting from the left to right\&.

.PP
.PP
.nf
let { x, y, \&.\&.\&.z } =  { x: 1, y: 2, z: 3 };
// x = 1
// y = 2
// z = { z: 3 }
.fi
.PP
.SS "New Syntax Errors:"
\fBSyntaxError\fP: The rest element has to be the last element when destructuring (1:10) 
.PP
.nf
> 1 | let { \&.\&.\&.x, y, z } = { x: 1, y: 2, z: 3};
    |           ^
# Previous behavior:
# x = { x: 1, y: 2, z: 3 }
# y = 2
# z = 3

.fi
.PP

.PP
Before, this was just a more verbose way of shallow copying \fRobj\fP since it doesn't actually do what you think\&.

.PP
\fBSyntaxError\fP: Cannot have multiple rest elements when destructuring (1:13)

.PP
.PP
.nf
> 1 | let { x, \&.\&.\&.y, \&.\&.\&.z } = { x: 1, y: 2, z: 3};
    |              ^
# Previous behavior:
# x = 1
# y = { y: 2, z: 3 }
# z = { y: 2, z: 3 }
.fi
.PP

.PP
Before y and z would just be the same value anyway so there is no reason to need to have both\&.

.PP
\fBSyntaxError\fP: A trailing comma is not permitted after the rest element (1:16)

.PP
.PP
.nf
let { x, y, \&.\&.\&.z, } = obj;
.fi
.PP

.PP
The rationale for this is that the use case for trailing comma is that you can add something at the end without affecting the line above\&. Since a RestProperty always has to be the last property it doesn't make sense\&.

.PP
.PP

.PP
get / set are valid property names in default assignment (#142) (\fR@jezell\fP)

.PP
.PP
.nf
// valid
function something({ set = null, get = null }) {}
.fi
.PP
.SH "v6\&.11\&.2 (2016-09-23)"
.PP
.SS "Bug Fix"
.IP "\(bu" 2
\fR#139\fP Don't do the duplicate check if not an identifier (#140) @hzoo
.PP

.PP
.PP
.nf
// regression with duplicate export check
SyntaxError: \&./typography\&.js: `undefined` has already been exported\&. Exported identifiers must be unique\&. (22:13)
  20 |
  21 | export const { rhythm } = typography;
> 22 | export const { TypographyStyle } = typography
.fi
.PP

.PP
Bail out for now, and make a change to account for destructuring in the next release\&.
.SH "6\&.11\&.1 (2016-09-22)"
.PP
.SS "Bug Fix"
.IP "\(bu" 2
\fR#137\fP - Fix a regression with duplicate exports - it was erroring on all keys in \fRObject\&.prototype\fP\&. @danez
.PP

.PP
.PP
.nf
export toString from '\&./toString';
.fi
.PP

.PP
.PP
.nf
`toString` has already been exported\&. Exported identifiers must be unique\&. (1:7)
> 1 | export toString from '\&./toString';
    |        ^
  2 |
.fi
.PP
.SH "6\&.11\&.0 (2016-09-22)"
.PP
.SS "Spec Compliance (will break CI)"
.IP "\(bu" 2
Disallow duplicate named exports (\fR#107\fP) @kaicataldo
.PP

.PP
.PP
.nf
// Only one default export allowed per module\&. (2:9)
export default function() {};
export { foo as default };

// Only one default export allowed per module\&. (2:0)
export default {};
export default function() {};

// `Foo` has already been exported\&. Exported identifiers must be unique\&. (2:0)
export { Foo };
export class Foo {};
.fi
.PP
.SS "New Feature (Syntax)"
.IP "\(bu" 2
Add support for computed class property names (\fR#121\fP) @motiz88
.PP

.PP
.PP
.nf
// AST
interface ClassProperty <: Node {
  type: "ClassProperty";
  key: Identifier;
  value: Expression;
  computed: boolean; // added
}
.fi
.PP

.PP
.PP
.nf
// with "plugins": ["classProperties"]
class Foo {
  [x]
  ['y']
}

class Bar {
  [p]
  [m] () {}
}
.fi
.PP
.SS "Bug Fix"
.IP "\(bu" 2
Fix \fRstatic\fP property falling through in the declare class Flow AST (\fR#135\fP) @danharper
.PP

.PP
.PP
.nf
declare class X {
    a: number;
    static b: number; // static
    c: number; // this was being marked as static in the AST as well
}
.fi
.PP
.SS "Polish"
.IP "\(bu" 2
Rephrase "assigning/binding to rvalue" errors to include context (\fR#119\fP) @motiz88
.PP

.PP
.PP
.nf
// Used to error with:
// SyntaxError: Assigning to rvalue (1:0)

// Now:
// Invalid left\-hand side in assignment expression (1:0)
3 = 4

// Invalid left\-hand side in for\-in statement (1:5)
for (+i in {});
.fi
.PP
.SS "Internal"
.IP "\(bu" 2
Fix call to \fRthis\&.parseMaybeAssign\fP with correct arguments (\fR#133\fP) @danez
.IP "\(bu" 2
Add semver note to changelog (\fR#131\fP) @hzoo
.PP
.SH "6\&.10\&.0 (2016-09-19)"
.PP
.RS 4
We plan to include some spec compliance bugs in patch versions\&. An example was the multiple default exports issue\&. 
.RE
.PP
.SS "Spec Compliance"
.IP "\(bu" 2
Implement ES2016 check for simple parameter list in strict mode (\fR#106\fP) (Timothy Gu)
.PP

.PP
.RS 4
It is a Syntax Error if ContainsUseStrict of FunctionBody is true and IsSimpleParameterList of FormalParameters is false\&. https://tc39.github.io/ecma262/2016/#sec-function-definitions-static-semantics-early-errors 
.RE
.PP

.PP
More Context: \fRtc39-notes\fP

.PP
For example:

.PP
.PP
.nf
// this errors because it uses destructuring and default parameters
// in a function with a "use strict" directive
function a([ option1, option2 ] = []) {
  "use strict";
}
.fi
.PP

.PP
The solution would be to use a top level "use strict" or to remove the destructuring or default parameters when using a function + "use strict" or to\&.
.SS "New Feature"
.IP "\(bu" 2
Exact object type annotations for Flow plugin (\fR#104\fP) (Basil Hosmer)
.PP

.PP
Added to flow in https://github.com/facebook/flow/commit/c710c40aa2a115435098d6c0dfeaadb023cd39b8

.PP
Looks like:

.PP
.PP
.nf
var a : {| x: number, y: string |} = { x: 0, y: 'foo' };
.fi
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Include \fRtypeParameter\fP location in \fRArrowFunctionExpression\fP (\fR#126\fP) (Daniel Tschinder)
.IP "\(bu" 2
Error on invalid flow type annotation with default assignment (\fR#122\fP) (Dan Harper)
.IP "\(bu" 2
Fix Flow return types on arrow functions (\fR#124\fP) (Dan Harper)
.PP
.SS "Misc"
.IP "\(bu" 2
Add tests for export extensions (\fR#127\fP) (Daniel Tschinder)
.IP "\(bu" 2
Fix Contributing guidelines [skip ci] (Daniel Tschinder)
.PP
.SH "6\&.9\&.2 (2016-09-09)"
.PP
The only change is to remove the \fRbabel-runtime\fP dependency by compiling with Babel's ES2015 loose mode\&. So using babylon standalone should be smaller\&.
.SH "6\&.9\&.1 (2016-08-23)"
.PP
This release contains mainly small bugfixes but also updates babylons default mode to es2017\&. The features for \fRexponentiationOperator\fP, \fRasyncFunctions\fP and \fRtrailingFunctionCommas\fP which previously needed to be activated via plugin are now enabled by default and the plugins are now no-ops\&.
.SS "Bug Fixes"
.IP "\(bu" 2
Fix issues with default object params in async functions (\fR#96\fP) @danez
.IP "\(bu" 2
Fix issues with flow-types and async function (\fR#95\fP) @danez
.IP "\(bu" 2
Fix arrow functions with destructuring, types & default value (\fR#94\fP) @danharper
.IP "\(bu" 2
Fix declare class with qualified type identifier (\fR#97\fP) @danez
.IP "\(bu" 2
Remove exponentiationOperator, asyncFunctions, trailingFunctionCommas plugins and enable them by default (\fR#98\fP) @danez
.PP
.SH "6\&.9\&.0 (2016-08-16)"
.PP
.SS "New syntax support"
.IP "\(bu" 2
Add JSX spread children (\fR#42\fP) @calebmer
.PP

.PP
(Be aware that React is not going to support this syntax)

.PP
.PP
.nf
<div>
  {\&.\&.\&.todos\&.map(todo => <Todo key={todo\&.id} todo={todo}/>)}
</div>
.fi
.PP

.PP
.IP "\(bu" 2
Add support for declare module\&.exports (\fR#72\fP) @danez
.PP

.PP
.PP
.nf
declare module "foo" {
  declare module\&.exports: {}
}
.fi
.PP
.SS "New Features"
.IP "\(bu" 2
If supplied, attach filename property to comment node loc\&. (\fR#80\fP) @divmain
.IP "\(bu" 2
Add identifier name to node loc field (\fR#90\fP) @kittens
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Fix exponential operator to behave according to spec (\fR#75\fP) @danez
.IP "\(bu" 2
Fix lookahead to not add comments to arrays which are not cloned (\fR#76\fP) @danez
.IP "\(bu" 2
Fix accidental fall-through in Flow type parsing\&. (\fR#82\fP) @xiemaisi
.IP "\(bu" 2
Only allow declares inside declare module (\fR#73\fP) @danez
.IP "\(bu" 2
Small fix for parsing type parameter declarations (\fR#83\fP) @gabelevi
.IP "\(bu" 2
Fix arrow param locations with flow types (\fR#57\fP) @danez
.IP "\(bu" 2
Fixes SyntaxError position with flow optional type (\fR#65\fP) @danez
.PP
.SS "Internal"
.IP "\(bu" 2
Add codecoverage to tests @danez
.IP "\(bu" 2
Fix tests to not save expected output if we expect the test to fail @danez
.IP "\(bu" 2
Make a shallow clone of babel for testing @danez
.IP "\(bu" 2
chore(package): update cross-env to version 2\&.0\&.0 (\fR#77\fP) @greenkeeperio-bot
.IP "\(bu" 2
chore(package): update ava to version 0\&.16\&.0 (\fR#86\fP) @greenkeeperio-bot
.IP "\(bu" 2
chore(package): update babel-plugin-istanbul to version 2\&.0\&.0 (\fR#89\fP) @greenkeeperio-bot
.IP "\(bu" 2
chore(package): update nyc to version 8\&.0\&.0 (\fR#88\fP) @greenkeeperio-bot
.PP
.SH "6\&.8\&.4 (2016-07-06)"
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Fix the location of params, when flow and default value used (\fR#68\fP) @danez
.PP
.SH "6\&.8\&.3 (2016-07-02)"
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Fix performance regression introduced in 6\&.8\&.2 with conditionals (\fR#63\fP) @danez
.PP
.SH "6\&.8\&.2 (2016-06-24)"
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Fix parse error with yielding jsx elements in generators \fRfunction* it() { yield <a></a>; }\fP (\fR#31\fP) @eldereal
.IP "\(bu" 2
When cloning nodes do not clone its comments (\fR#24\fP) @danez
.IP "\(bu" 2
Fix parse errors when using arrow functions with an spread element and return type \fR(\&.\&.\&.props): void => {}\fP (\fR#10\fP) @danez
.IP "\(bu" 2
Fix leading comments added from previous node (\fR#23\fP) @danez
.IP "\(bu" 2
Fix parse errors with flow's optional arguments \fR(arg?) => {}\fP (\fR#19\fP) @danez
.IP "\(bu" 2
Support negative numeric type literals @kittens
.IP "\(bu" 2
Remove line terminator restriction after await keyword @kittens
.IP "\(bu" 2
Remove grouped type arrow restriction as it seems flow no longer has it @kittens
.IP "\(bu" 2
Fix parse error with generic methods that have the name \fRget\fP or \fRset\fP \fRclass foo { get() {} }\fP (\fR#55\fP) @vkurchatkin
.IP "\(bu" 2
Fix parse error with arrow functions that have flow type parameter declarations \fR<T>(x: T): T => x;\fP (\fR#54\fP) @gabelevi
.PP
.SS "Documentation"
.IP "\(bu" 2
Document AST differences from ESTree (\fR#41\fP) @nene
.IP "\(bu" 2
Move ast spec from babel/babel (\fR#46\fP) @hzoo
.PP
.SS "Internal"
.IP "\(bu" 2
Enable skipped tests (\fR#16\fP) @danez
.IP "\(bu" 2
Add script to test latest version of babylon with babel (\fR#21\fP) @danez
.IP "\(bu" 2
Upgrade test runner ava @kittens
.IP "\(bu" 2
Add missing generate-identifier-regex script @kittens
.IP "\(bu" 2
Rename parser context types @kittens
.IP "\(bu" 2
Add node v6 to travis testing @hzoo
.IP "\(bu" 2
Update to Unicode v9 (\fR#45\fP) @mathiasbynens
.PP
.SH "6\&.8\&.1 (2016-06-06)"
.PP
.SS "New Feature"
.IP "\(bu" 2
Parse type parameter declarations with defaults like \fRtype Foo<T = string> = T\fP
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Type parameter declarations need 1 or more type parameters\&.
.IP "\(bu" 2
The existential type \fR*\fP is not a valid type parameter\&.
.IP "\(bu" 2
The existential type \fR*\fP is a primary type
.PP
.SS "Spec Compliance"
.IP "\(bu" 2
The param list for type parameter declarations now consists of \fRTypeParameter\fP nodes
.IP "\(bu" 2
New \fRTypeParameter\fP AST Node (replaces using the \fRIdentifier\fP node before)
.PP

.PP
.PP
.nf
interface TypeParameter <: Node {
  bound: TypeAnnotation;
  default: TypeAnnotation;
  name: string;
  variance: "plus" | "minus";
}
.fi
.PP
.SH "6\&.8\&.0 (2016-05-02)"
.PP
.SS "New Feature"
.SS "Parse Method Parameter Decorators (\fR#12\fP)"
.RS 4
\fRMethod Parameter Decorators\fP is now a TC39 \fRstage 0 proposal\fP\&. 
.RE
.PP

.PP
Examples:

.PP
.PP
.nf
class Foo {
  constructor(@foo() x, @bar({ a: 123 }) @baz() y) {}
}

export default function func(@foo() x, @bar({ a: 123 }) @baz() y) {}

var obj = {
  method(@foo() x, @bar({ a: 123 }) @baz() y) {}
};
.fi
.PP
.SS "Parse for-await statements (w/ \fRasyncGenerators\fP plugin) (\fR#17\fP)"
There is also a new node type, \fRForAwaitStatement\fP\&.

.PP
.RS 4
\fRAsync generators and for-await\fP are now a \fRstage 2 proposal\fP\&. 
.RE
.PP

.PP
Example:

.PP
.PP
.nf
async function f() {
  for await (let x of y);
}
.fi
.PP
 
