.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2deep-is_2_r_e_a_d_m_e" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2deep-is_2_r_e_a_d_m_e \- deep-is 
.PP
Node's \fRassert\&.deepEqual() algorithm\fP as a standalone module\&. Exactly like \fRdeep-equal\fP except for the fact that \fRdeepEqual(NaN, NaN) === true\fP\&.

.PP
This module is around \fR5 times faster\fP than wrapping \fRassert\&.deepEqual()\fP in a \fRtry/catch\fP\&.

.PP
\fR\fP
.PP
\fR\fP.SH "example"
.PP
.PP
.nf
 js
var equal = require('deep\-is');
console\&.dir([
    equal(
        { a : [ 2, 3 ], b : [ 4 ] },
        { a : [ 2, 3 ], b : [ 4 ] }
    ),
    equal(
        { x : 5, y : [6] },
        { x : 5, y : 6 }
    )
]);
.fi
.PP
.SH "methods"
.PP
var deepIs = require('deep-is')
.SS "deepIs(a, b)"
Compare objects \fRa\fP and \fRb\fP, returning whether they are equal according to a recursive equality algorithm\&.
.SH "install"
.PP
With \fRnpm\fP do:

.PP
.PP
.nf
npm install deep\-is
.fi
.PP
.SH "test"
.PP
With \fRnpm\fP do:

.PP
.PP
.nf
npm test
.fi
.PP
.SH "license"
.PP
Copyright (c) 2012, 2013 Thorsten Lorenz thlorenz@gmx.de Copyright (c) 2012 James Halliday mail@substack.net

.PP
Derived largely from node's assert module, which has the copyright statement:

.PP
Copyright (c) 2009 Thomas Robinson <280north\&.com>

.PP
Released under the MIT license, see LICENSE for details\&. 
