.TH "md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2picomatch_2_c_h_a_n_g_e_l_o_g" 3 "PinterestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_pinterest_app_2_web_photo_page_2_frontend_2node__modules_2picomatch_2_c_h_a_n_g_e_l_o_g \- Release history 
.PP


.PP
\fBAll notable changes to this project will be documented in this file\&.\fP

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.

.PP
\fB\fBGuiding Principles\fP\fP
.PP
.PP
.RS 4


.PP
.IP "\(bu" 2
Changelogs are for humans, not machines\&.
.IP "\(bu" 2
There should be an entry for every single version\&.
.IP "\(bu" 2
The same types of changes should be grouped\&.
.IP "\(bu" 2
Versions and sections should be linkable\&.
.IP "\(bu" 2
The latest version comes first\&.
.IP "\(bu" 2
The release date of each versions is displayed\&.
.IP "\(bu" 2
Mention whether you follow Semantic Versioning\&.
.PP

.PP
.RE
.PP

.PP
\fB\fBTypes of changes\fP\fP
.PP
.PP
.RS 4


.PP
Changelog entries are classified using the following labels \fI(from \fRkeep-a-changelog\fP\fP):

.PP
.IP "\(bu" 2
\fRAdded\fP for new features\&.
.IP "\(bu" 2
\fRChanged\fP for changes in existing functionality\&.
.IP "\(bu" 2
\fRDeprecated\fP for soon-to-be removed features\&.
.IP "\(bu" 2
\fRRemoved\fP for now removed features\&.
.IP "\(bu" 2
\fRFixed\fP for any bug fixes\&.
.IP "\(bu" 2
\fRSecurity\fP in case of vulnerabilities\&.
.PP

.PP
.RE
.PP
.SH "2\&.3\&.1 (2022-01-02)"
.PP
.SS "Fixed"
.IP "\(bu" 2
Fixes bug when a pattern containing an expression after the closing parenthesis (\fR/!(*\&.d)\&.{ts,tsx}\fP) was incorrectly converted to regexp (\fR9f241ef\fP)\&.
.PP
.SS "Changed"
.IP "\(bu" 2
Some documentation improvements (\fRf81d236\fP, \fR421e0e7\fP)\&.
.PP
.SH "2\&.3\&.0 (2021-05-21)"
.PP
.SS "Fixed"
.IP "\(bu" 2
Fixes bug where file names with two dots were not being matched consistently with negation extglobs containing a star (\fR56083ef\fP)
.PP
.SH "2\&.2\&.3 (2021-04-10)"
.PP
.SS "Fixed"
.IP "\(bu" 2
Do not skip pattern seperator for square brackets (\fRfb08a30\fP)\&.
.IP "\(bu" 2
Set negatedExtGlob also if it does not span the whole pattern (\fR032e3f5\fP)\&.
.PP
.SH "2\&.2\&.2 (2020-03-21)"
.PP
.SS "Fixed"
.IP "\(bu" 2
Correctly handle parts of the pattern after parentheses in the \fRscan\fP method (\fRe15b920\fP)\&.
.PP
.SH "2\&.2\&.1 (2020-01-04)"
.PP
.IP "\(bu" 2
Fixes \fR#49\fP, so that braces with no sets or ranges are now propertly treated as literals\&.
.PP
.SH "2\&.2\&.0 (2020-01-04)"
.PP
.IP "\(bu" 2
Disable fastpaths mode for the parse method (\fR5b8d33f\fP)
.IP "\(bu" 2
Add \fRtokens\fP, \fRslashes\fP, and \fRparts\fP to the object returned by \fRpicomatch\&.scan()\fP\&.
.PP
.SH "2\&.1\&.0 (2019-10-31)"
.PP
.IP "\(bu" 2
add benchmarks for scan (\fR4793b92\fP)
.IP "\(bu" 2
Add eslint object-curly-spacing rule (\fR707c650\fP)
.IP "\(bu" 2
Add prefer-const eslint rule (\fR5c7501c\fP)
.IP "\(bu" 2
Add support for nonegate in scan API (\fR275c9b9\fP)
.IP "\(bu" 2
Change lets to consts\&. Move root import up\&. (\fR4840625\fP)
.IP "\(bu" 2
closes https://github.com/micromatch/picomatch/issues/21 (\fR766bcb0\fP)
.IP "\(bu" 2
Fix "Extglobs" table in readme (\fReb19da8\fP)
.IP "\(bu" 2
fixes https://github.com/micromatch/picomatch/issues/20 (\fR9caca07\fP)
.IP "\(bu" 2
fixes https://github.com/micromatch/picomatch/issues/26 (\fRfa58f45\fP)
.IP "\(bu" 2
Lint test (\fRd433a34\fP)
.IP "\(bu" 2
lint unit tests (\fR0159b55\fP)
.IP "\(bu" 2
Make scan work with noext (\fR6c02e03\fP)
.IP "\(bu" 2
minor linting (\fRc2a2b87\fP)
.IP "\(bu" 2
minor parser improvements (\fR197671d\fP)
.IP "\(bu" 2
remove eslint since it\&.\&.\&. (\fR07876fa\fP)
.IP "\(bu" 2
remove funding file (\fR8ebe96d\fP)
.IP "\(bu" 2
Remove unused funks (\fRcbc6d54\fP)
.IP "\(bu" 2
Run eslint during pretest, fix existing eslint findings (\fR0682367\fP)
.IP "\(bu" 2
support \fRnoparen\fP in scan (\fR3d37569\fP)
.IP "\(bu" 2
update changelog (\fR7b34e77\fP)
.IP "\(bu" 2
update travis (\fR777f038\fP)
.IP "\(bu" 2
Use eslint-disable-next-line instead of eslint-disable (\fR4e7c1fd\fP)
.PP
.SH "2\&.0\&.7 (2019-05-14)"
.PP
.IP "\(bu" 2
2\&.0\&.7 (\fR9eb9a71\fP)
.IP "\(bu" 2
supports lookbehinds (\fR1f63f7e\fP)
.IP "\(bu" 2
update \&.verb\&.md file with typo change (\fR2741279\fP)
.IP "\(bu" 2
fix: typo in README (\fR0753e44\fP)
.PP
.SH "2\&.0\&.4 (2019-04-10)"
.PP
.SS "Fixed"
.IP "\(bu" 2
Readme link \fRfixed\fP by @danez\&.
.IP "\(bu" 2
\fRoptions\&.capture\fP now works as expected when fastpaths are enabled\&. See https://github.com/micromatch/picomatch/pull/12/commits/26aefd71f1cfaf95c37f1c1fcab68a693b037304\&. Thanks to @DrPizza\&.
.PP
.SH "2\&.0\&.0 (2019-04-10)"
.PP
.SS "Added"
.IP "\(bu" 2
Adds support for \fRoptions\&.onIgnore\fP\&. See the readme for details
.IP "\(bu" 2
Adds support for \fRoptions\&.onResult\fP\&. See the readme for details
.PP
.SS "Breaking changes"
.IP "\(bu" 2
The unixify option was renamed to \fRwindows\fP
.IP "\(bu" 2
caching and all related options and methods have been removed
.PP
.SH "1\&.0\&.0 (2018-11-05)"
.PP
.IP "\(bu" 2
adds \fR\&.onMatch\fP option
.IP "\(bu" 2
improvements to \fR\&.scan\fP method
.IP "\(bu" 2
numerous improvements and optimizations for matching and parsing
.IP "\(bu" 2
better windows path handling
.PP
.SH "0\&.1\&.0 - 2017-04-13"
.PP
First release\&. 
